# Environment Setup

In [ ]:
# !pip install optuna

Collecting optuna
  Downloading optuna-4.6.0-py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (1.17.2)
Collecting colorlog (from optuna)
  Downloading colorlog-6.10.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (25.0)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.44)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from optuna) (4.67.1)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from optuna) (6.0.3)
Requirement already satisfied: Mako in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (1.3.10)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (4.15.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.4.2->optuna) (3.3.0)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.12/dist-packages (from Mako->alembic>=1.5.0->optuna) (3.0.3)
Downloading optuna-4.6.0-py3-none-any.whl (404 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 404.7/404.7 kB 10.8 MB/s eta 0:00:00
Downloading colorlog-6.10.1-py3-none-any.whl (11 kB)
Installing collected packages: colorlog, optuna
Successfully installed colorlog-6.10.1 optuna-4.6.0

# Train–Test Split

In [2]:
import pandas as pd

df = pd.read_csv('Data/cell2cell-duke univeristy.csv')
df = df.drop(columns=['Unnamed: 0', 'X', 'customer', 'churndep', 'traintest'])
df

,churn,revenue,mou,recchrge,directas,overage,roam,changem,changer,dropvce,...,retaccpt,newcelly,newcelln,refer,incmiss,income,mcycle,setprcm,setprc,retcall
0,0,57.492500,482.75,37.424999,0.2475,22.75,0.0,532.25,50.987499,8.333333,...,0,0,1,0,0,5,0,0,149.989990,0
1,0,82.275002,1312.25,75.000000,1.2375,0.00,0.0,156.75,8.145000,52.000000,...,0,1,0,0,0,6,0,0,9.989998,0
2,0,31.662500,25.50,29.990000,0.2475,0.00,0.0,59.50,4.027500,0.000000,...,0,0,1,0,0,9,0,0,29.989990,0
3,0,62.127499,97.50,65.985001,2.4750,0.00,0.0,23.50,6.822500,0.000000,...,0,1,0,0,0,6,0,0,29.989990,0
4,0,25.225000,2.50,25.000000,0.0000,0.00,0.0,-2.50,-0.225000,0.000000,...,0,1,0,0,0,7,0,0,29.989990,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71042,1,117.489998,384.00,29.990000,0.0000,250.00,0.0,0.00,0.000000,4.000000,...,0,0,0,0,0,2,0,0,29.989990,0
71043,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,...,0,0,0,0,0,6,0,1,0.000000,0
71044,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.333333,...,0,0,0,0,0,6,0,0,59.989990,0
71045,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,...,0,1,0,0,0,8,0,1,0.000000,0
71046,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,71.666664,...,0,0,0,0,0,7,0,0,79.989990,0

In [3]:
df= df.dropna()

In [4]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

y = df['churn'].astype(int)

df = pd.DataFrame(df)
label_encoder = LabelEncoder()


X=df.drop(['churn'], axis=1)

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Base model

In [6]:
import numpy as np
import optuna
import time
import xgboost as xgb
from sklearn.datasets import make_classification
from sklearn.metrics import (accuracy_score, precision_score, recall_score,
                             f1_score, matthews_corrcoef, confusion_matrix, classification_report, roc_auc_score)
from imblearn.over_sampling import SMOTE

overall_start_time = time.time()

smote = SMOTE(random_state=42)
X_resampled, y_resampled = smote.fit_resample(X_train, y_train)

def objective(trial):
    max_depth = trial.suggest_int('max_depth', 2, 10)
    learning_rate = trial.suggest_float('learning_rate', 0.01, 0.3)
    n_estimators = trial.suggest_int('n_estimators', 100, 500)

    model = xgb.XGBClassifier(
        objective='binary:logistic',
        max_depth=max_depth,
        learning_rate=learning_rate,
        n_estimators=n_estimators,
        verbosity=0,
        use_label_encoder=False
    )

    model.fit(X_resampled, y_resampled)
    y_prob = model.predict_proba(X_test)[:, 1]

    return roc_auc_score(y_test, y_prob)


start_time = time.time()


study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=200)

end_time = time.time()

total_time = end_time - start_time
print(f"Thời gian chạy tìm kiếm siêu tham số: {total_time:.2f} Giây")

best_params = study.best_params
print("Siêu tham số tối ưu:", best_params)

best_model = xgb.XGBClassifier(
    objective='binary:logistic',
    # scale_pos_weight=scale_pos_weight,
    max_depth=best_params['max_depth'],
    learning_rate=best_params['learning_rate'],
    n_estimators=best_params['n_estimators'],
    verbosity=0,
    use_label_encoder=False
)
best_model.fit(X_resampled, y_resampled)

# Dự đoán
y_pred = best_model.predict(X_test)
y_prob = best_model.predict_proba(X_test)[:, 1]

# Tính toán các chỉ số đánh giá
auc_score = roc_auc_score(y_test, y_prob)
print("AUC:", auc_score)
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))
print("Recall:", recall_score(y_test, y_pred))
print("F1 Score:", f1_score(y_test, y_pred))
print("Matthews Correlation Coefficient:", matthews_corrcoef(y_test, y_pred))

print("\nMa trận nhầm lẫn:")
print(confusion_matrix(y_test, y_pred))

print("\nBáo cáo phân loại:")
print(classification_report(y_test, y_pred))

# Ghi lại thời gian kết thúc toàn bộ quá trình
overall_end_time = time.time()

# Tính tổng thời gian chạy toàn bộ
overall_total_time = overall_end_time - overall_start_time
print(f"Toàn bộ thời gian chạy: {overall_total_time:.2f} Giây")

c:\Users\ADMIN\AppData\Local\Programs\Python\Python312\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
[I 2025-12-15 22:42:19,215] A new study created in memory with name: no-name-053b3b05-304a-4a07-81f5-2cc20abd54af
[I 2025-12-15 22:42:20,764] Trial 0 finished with value: 0.6460467060916442 and parameters: {'max_depth': 10, 'learning_rate': 0.23889054599109688, 'n_estimators': 330}. Best is trial 0 with value: 0.6460467060916442.
[I 2025-12-15 22:42:21,489] Trial 1 finished with value: 0.6624778865607378 and parameters: {'max_depth': 6, 'learning_rate': 0.13877329529788449, 'n_estimators': 396}. Best is trial 1 with value: 0.6624778865607378.
[I 2025-12-15 22:42:22,296] Trial 2 finished with value: 0.6499184887199725 and parameters: {'max_depth': 8, 'learning_rate': 0.18358067054184538, 'n_estimators': 281}. Best is trial 1 with value: 0.6624778865607378.
[I 2025-12-15 22:42:23,557] Trial 3 finished with value: 0.6644639934331021 and parameters: {'max_depth': 8, 'learning_rate': 0.06457252523376078, 'n_estimators': 478}. Best is trial 3 with value: 0.6644639934331021.
[I 2025-12-15 22:42:25,300] Trial 4 finished with value: 0.6539709153619147 and parameters: {'max_depth': 10, 'learning_rate': 0.12859797304902165, 'n_estimators': 417}. Best is trial 3 with value: 0.6644639934331021.
[I 2025-12-15 22:42:26,139] Trial 5 finished with value: 0.6596101104904737 and parameters: {'max_depth': 6, 'learning_rate': 0.15140319215968803, 'n_estimators': 472}. Best is trial 3 with value: 0.6644639934331021.
[I 2025-12-15 22:42:26,753] Trial 6 finished with value: 0.6556004809829309 and parameters: {'max_depth': 5, 'learning_rate': 0.2822211348544021, 'n_estimators': 402}. Best is trial 3 with value: 0.6644639934331021.
[I 2025-12-15 22:42:27,025] Trial 7 finished with value: 0.6634240179904329 and parameters: {'max_depth': 4, 'learning_rate': 0.1914109639560145, 'n_estimators': 211}. Best is trial 3 with value: 0.6644639934331021.
[I 2025-12-15 22:42:29,008] Trial 8 finished with value: 0.6504504068405761 and parameters: {'max_depth': 10, 'learning_rate': 0.12281596758056752, 'n_estimators': 476}. Best is trial 3 with value: 0.6644639934331021.
[I 2025-12-15 22:42:29,593] Trial 9 finished with value: 0.6544632474023904 and parameters: {'max_depth': 7, 'learning_rate': 0.179755208001108, 'n_estimators': 249}. Best is trial 3 with value: 0.6644639934331021.
[I 2025-12-15 22:42:29,739] Trial 10 finished with value: 0.5862644399397174 and parameters: {'max_depth': 2, 'learning_rate': 0.026657626416243148, 'n_estimators': 105}. Best is trial 3 with value: 0.6644639934331021.
[I 2025-12-15 22:42:29,976] Trial 11 finished with value: 0.6244126023498165 and parameters: {'max_depth': 3, 'learning_rate': 0.05243338865028707, 'n_estimators': 183}. Best is trial 3 with value: 0.6644639934331021.
[I 2025-12-15 22:42:30,263] Trial 12 finished with value: 0.6492743994624112 and parameters: {'max_depth': 4, 'learning_rate': 0.07447146172925491, 'n_estimators': 201}. Best is trial 3 with value: 0.6644639934331021.
[I 2025-12-15 22:42:31,289] Trial 13 finished with value: 0.6496324764353673 and parameters: {'max_depth': 8, 'learning_rate': 0.21514718676348293, 'n_estimators': 337}. Best is trial 3 with value: 0.6644639934331021.
[I 2025-12-15 22:42:31,517] Trial 14 finished with value: 0.6440013279803578 and parameters: {'max_depth': 4, 'learning_rate': 0.08487084663549373, 'n_estimators': 144}. Best is trial 3 with value: 0.6644639934331021.
[I 2025-12-15 22:42:32,229] Trial 15 finished with value: 0.6472501787719563 and parameters: {'max_depth': 8, 'learning_rate': 0.2429121519398756, 'n_estimators': 241}. Best is trial 3 with value: 0.6644639934331021.
[I 2025-12-15 22:42:32,518] Trial 16 finished with value: 0.6336175399816236 and parameters: {'max_depth': 2, 'learning_rate': 0.09618215785051858, 'n_estimators': 337}. Best is trial 3 with value: 0.6644639934331021.
[I 2025-12-15 22:42:32,868] Trial 17 finished with value: 0.6377816047001306 and parameters: {'max_depth': 5, 'learning_rate': 0.026970165757681776, 'n_estimators': 213}. Best is trial 3 with value: 0.6644639934331021.
[I 2025-12-15 22:42:33,502] Trial 18 finished with value: 0.6579535872438749 and parameters: {'max_depth': 7, 'learning_rate': 0.18313579501505756, 'n_estimators': 285}. Best is trial 3 with value: 0.6644639934331021.
[I 2025-12-15 22:42:35,226] Trial 19 finished with value: 0.648419687890094 and parameters: {'max_depth': 9, 'learning_rate': 0.2814463630560398, 'n_estimators': 500}. Best is trial 3 with value: 0.6644639934331021.
[I 2025-12-15 22:42:35,427] Trial 20 finished with value: 0.6395018413555918 and parameters: {'max_depth': 3, 'learning_rate': 0.11524543256708282, 'n_estimators': 146}. Best is trial 3 with value: 0.6644639934331021.
[I 2025-12-15 22:42:36,154] Trial 21 finished with value: 0.6553395098448767 and parameters: {'max_depth': 6, 'learning_rate': 0.1545866176127863, 'n_estimators': 412}. Best is trial 3 with value: 0.6644639934331021.
[I 2025-12-15 22:42:36,833] Trial 22 finished with value: 0.6686031566161134 and parameters: {'max_depth': 6, 'learning_rate': 0.057154166760595836, 'n_estimators': 383}. Best is trial 22 with value: 0.6686031566161134.
[I 2025-12-15 22:42:37,472] Trial 23 finished with value: 0.6667871975443888 and parameters: {'max_depth': 5, 'learning_rate': 0.05673265308689779, 'n_estimators': 443}. Best is trial 22 with value: 0.6686031566161134.
[I 2025-12-15 22:42:38,394] Trial 24 finished with value: 0.6653994763468539 and parameters: {'max_depth': 7, 'learning_rate': 0.04652642758623362, 'n_estimators': 447}. Best is trial 22 with value: 0.6686031566161134.
[I 2025-12-15 22:42:39,064] Trial 25 finished with value: 0.6347104407061568 and parameters: {'max_depth': 5, 'learning_rate': 0.011543458991857644, 'n_estimators': 438}. Best is trial 22 with value: 0.6686031566161134.
[I 2025-12-15 22:42:40,047] Trial 26 finished with value: 0.6670321641787427 and parameters: {'max_depth': 7, 'learning_rate': 0.04920495877797101, 'n_estimators': 447}. Best is trial 22 with value: 0.6686031566161134.
[I 2025-12-15 22:42:40,709] Trial 27 finished with value: 0.6669868032776919 and parameters: {'max_depth': 6, 'learning_rate': 0.09844195254411552, 'n_estimators': 378}. Best is trial 22 with value: 0.6686031566161134.
[I 2025-12-15 22:42:41,380] Trial 28 finished with value: 0.6656111901662238 and parameters: {'max_depth': 6, 'learning_rate': 0.10631262481159082, 'n_estimators': 374}. Best is trial 22 with value: 0.6686031566161134.
[I 2025-12-15 22:42:42,177] Trial 29 finished with value: 0.6668477633585506 and parameters: {'max_depth': 7, 'learning_rate': 0.08304606736538894, 'n_estimators': 360}. Best is trial 22 with value: 0.6686031566161134.
[I 2025-12-15 22:42:43,461] Trial 30 finished with value: 0.6634872871823014 and parameters: {'max_depth': 9, 'learning_rate': 0.030448554180587645, 'n_estimators': 375}. Best is trial 22 with value: 0.6686031566161134.
[I 2025-12-15 22:42:44,224] Trial 31 finished with value: 0.6644291922045958 and parameters: {'max_depth': 7, 'learning_rate': 0.08990689606931906, 'n_estimators': 356}. Best is trial 22 with value: 0.6686031566161134.
[I 2025-12-15 22:42:44,767] Trial 32 finished with value: 0.6673036696055132 and parameters: {'max_depth': 6, 'learning_rate': 0.07820520965312008, 'n_estimators': 315}. Best is trial 22 with value: 0.6686031566161134.
[I 2025-12-15 22:42:45,314] Trial 33 finished with value: 0.6628096912714736 and parameters: {'max_depth': 6, 'learning_rate': 0.044870990510897324, 'n_estimators': 306}. Best is trial 22 with value: 0.6686031566161134.
[I 2025-12-15 22:42:45,866] Trial 34 finished with value: 0.6666808393040963 and parameters: {'max_depth': 6, 'learning_rate': 0.06979413744466786, 'n_estimators': 318}. Best is trial 22 with value: 0.6686031566161134.
[I 2025-12-15 22:42:46,415] Trial 35 finished with value: 0.6650272986573147 and parameters: {'max_depth': 5, 'learning_rate': 0.0650060249902782, 'n_estimators': 384}. Best is trial 22 with value: 0.6686031566161134.
[I 2025-12-15 22:42:47,574] Trial 36 finished with value: 0.6604825907425533 and parameters: {'max_depth': 8, 'learning_rate': 0.1038756232684121, 'n_estimators': 433}. Best is trial 22 with value: 0.6686031566161134.
[I 2025-12-15 22:42:48,063] Trial 37 finished with value: 0.6633429039673172 and parameters: {'max_depth': 6, 'learning_rate': 0.13570857032252268, 'n_estimators': 271}. Best is trial 22 with value: 0.6686031566161134.
[I 2025-12-15 22:42:48,842] Trial 38 finished with value: 0.6499524395902329 and parameters: {'max_depth': 7, 'learning_rate': 0.01658073911890895, 'n_estimators': 352}. Best is trial 22 with value: 0.6686031566161134.
[I 2025-12-15 22:42:49,429] Trial 39 finished with value: 0.6602421297377106 and parameters: {'max_depth': 5, 'learning_rate': 0.04002666145841319, 'n_estimators': 398}. Best is trial 22 with value: 0.6686031566161134.
[I 2025-12-15 22:42:50,488] Trial 40 finished with value: 0.6612445498065105 and parameters: {'max_depth': 9, 'learning_rate': 0.07519952671992325, 'n_estimators': 318}. Best is trial 22 with value: 0.6686031566161134.
[I 2025-12-15 22:42:51,132] Trial 41 finished with value: 0.6659495185208153 and parameters: {'max_depth': 6, 'learning_rate': 0.08590234419255321, 'n_estimators': 369}. Best is trial 22 with value: 0.6686031566161134.
[I 2025-12-15 22:42:52,027] Trial 42 finished with value: 0.6626170914747627 and parameters: {'max_depth': 7, 'learning_rate': 0.11630314283492646, 'n_estimators': 424}. Best is trial 22 with value: 0.6686031566161134.
[I 2025-12-15 22:42:52,996] Trial 43 finished with value: 0.6677856577359844 and parameters: {'max_depth': 7, 'learning_rate': 0.0599831927709541, 'n_estimators': 456}. Best is trial 22 with value: 0.6686031566161134.
[I 2025-12-15 22:42:54,219] Trial 44 finished with value: 0.6641061576065141 and parameters: {'max_depth': 8, 'learning_rate': 0.06314778203443859, 'n_estimators': 469}. Best is trial 22 with value: 0.6686031566161134.
[I 2025-12-15 22:42:55,177] Trial 45 finished with value: 0.6654611971252002 and parameters: {'max_depth': 7, 'learning_rate': 0.03600745790807243, 'n_estimators': 463}. Best is trial 22 with value: 0.6686031566161134.
[I 2025-12-15 22:42:55,853] Trial 46 finished with value: 0.666515336744023 and parameters: {'max_depth': 6, 'learning_rate': 0.05344508830383382, 'n_estimators': 394}. Best is trial 22 with value: 0.6686031566161134.
[I 2025-12-15 22:42:57,169] Trial 47 finished with value: 0.6549751503744331 and parameters: {'max_depth': 8, 'learning_rate': 0.1319046199124687, 'n_estimators': 496}. Best is trial 22 with value: 0.6686031566161134.
[I 2025-12-15 22:42:57,826] Trial 48 finished with value: 0.6670032519983864 and parameters: {'max_depth': 5, 'learning_rate': 0.16826025754869273, 'n_estimators': 457}. Best is trial 22 with value: 0.6686031566161134.
[I 2025-12-15 22:42:58,368] Trial 49 finished with value: 0.667987839927853 and parameters: {'max_depth': 4, 'learning_rate': 0.14691057469612895, 'n_estimators': 455}. Best is trial 22 with value: 0.6686031566161134.
[I 2025-12-15 22:42:58,857] Trial 50 finished with value: 0.6675358174066098 and parameters: {'max_depth': 4, 'learning_rate': 0.20450231922449086, 'n_estimators': 420}. Best is trial 22 with value: 0.6686031566161134.
[I 2025-12-15 22:42:59,374] Trial 51 finished with value: 0.6656811860725739 and parameters: {'max_depth': 4, 'learning_rate': 0.23291086372691888, 'n_estimators': 415}. Best is trial 22 with value: 0.6686031566161134.
[I 2025-12-15 22:42:59,776] Trial 52 finished with value: 0.6688310907017235 and parameters: {'max_depth': 3, 'learning_rate': 0.205811142991579, 'n_estimators': 420}. Best is trial 52 with value: 0.6688310907017235.
[I 2025-12-15 22:43:00,243] Trial 53 finished with value: 0.6687396073847751 and parameters: {'max_depth': 3, 'learning_rate': 0.19929290219719498, 'n_estimators': 487}. Best is trial 52 with value: 0.6688310907017235.
[I 2025-12-15 22:43:00,728] Trial 54 finished with value: 0.6691602808781515 and parameters: {'max_depth': 3, 'learning_rate': 0.20058711029320403, 'n_estimators': 486}. Best is trial 54 with value: 0.6691602808781515.
[I 2025-12-15 22:43:01,189] Trial 55 finished with value: 0.6698055124079834 and parameters: {'max_depth': 3, 'learning_rate': 0.19804264588613119, 'n_estimators': 482}. Best is trial 55 with value: 0.6698055124079834.
[I 2025-12-15 22:43:01,660] Trial 56 finished with value: 0.6687904765765522 and parameters: {'max_depth': 3, 'learning_rate': 0.2045782685640359, 'n_estimators': 481}. Best is trial 55 with value: 0.6698055124079834.
[I 2025-12-15 22:43:02,126] Trial 57 finished with value: 0.6706897961401909 and parameters: {'max_depth': 3, 'learning_rate': 0.19858992126620245, 'n_estimators': 495}. Best is trial 57 with value: 0.6706897961401909.
[I 2025-12-15 22:43:02,624] Trial 58 finished with value: 0.6691818063644923 and parameters: {'max_depth': 3, 'learning_rate': 0.19793162697980893, 'n_estimators': 487}. Best is trial 57 with value: 0.6706897961401909.
[I 2025-12-15 22:43:02,994] Trial 59 finished with value: 0.6611149907472137 and parameters: {'max_depth': 2, 'learning_rate': 0.21968591852130692, 'n_estimators': 484}. Best is trial 57 with value: 0.6706897961401909.
[I 2025-12-15 22:43:03,446] Trial 60 finished with value: 0.6671025916101727 and parameters: {'max_depth': 3, 'learning_rate': 0.17016814005826758, 'n_estimators': 477}. Best is trial 57 with value: 0.6706897961401909.
[I 2025-12-15 22:43:03,921] Trial 61 finished with value: 0.6674571783067469 and parameters: {'max_depth': 3, 'learning_rate': 0.19820986912020536, 'n_estimators': 486}. Best is trial 57 with value: 0.6706897961401909.
[I 2025-12-15 22:43:04,310] Trial 62 finished with value: 0.6667065531220954 and parameters: {'max_depth': 2, 'learning_rate': 0.2529445743463375, 'n_estimators': 500}. Best is trial 57 with value: 0.6706897961401909.
[I 2025-12-15 22:43:04,789] Trial 63 finished with value: 0.6672690460638045 and parameters: {'max_depth': 3, 'learning_rate': 0.21405811793477011, 'n_estimators': 484}. Best is trial 57 with value: 0.6706897961401909.
[I 2025-12-15 22:43:05,240] Trial 64 finished with value: 0.669103459178654 and parameters: {'max_depth': 3, 'learning_rate': 0.19353304610896874, 'n_estimators': 470}. Best is trial 57 with value: 0.6706897961401909.
[I 2025-12-15 22:43:05,644] Trial 65 finished with value: 0.6588403205155071 and parameters: {'max_depth': 2, 'learning_rate': 0.18622944357034613, 'n_estimators': 472}. Best is trial 57 with value: 0.6706897961401909.
[I 2025-12-15 22:43:06,107] Trial 66 finished with value: 0.6661355946736707 and parameters: {'max_depth': 3, 'learning_rate': 0.22797113828050836, 'n_estimators': 467}. Best is trial 57 with value: 0.6706897961401909.
[I 2025-12-15 22:43:06,521] Trial 67 finished with value: 0.6674252835265733 and parameters: {'max_depth': 3, 'learning_rate': 0.24733834767495363, 'n_estimators': 434}. Best is trial 57 with value: 0.6706897961401909.
[I 2025-12-15 22:43:07,009] Trial 68 finished with value: 0.6685580749371731 and parameters: {'max_depth': 3, 'learning_rate': 0.17108132399930684, 'n_estimators': 492}. Best is trial 57 with value: 0.6706897961401909.
[I 2025-12-15 22:43:07,360] Trial 69 finished with value: 0.6635641494141883 and parameters: {'max_depth': 2, 'learning_rate': 0.2666179891847297, 'n_estimators': 448}. Best is trial 57 with value: 0.6706897961401909.
[I 2025-12-15 22:43:07,914] Trial 70 finished with value: 0.6677545879302282 and parameters: {'max_depth': 4, 'learning_rate': 0.20738821068685342, 'n_estimators': 472}. Best is trial 57 with value: 0.6706897961401909.
[I 2025-12-15 22:43:08,386] Trial 71 finished with value: 0.668756576473948 and parameters: {'max_depth': 3, 'learning_rate': 0.1963381580956031, 'n_estimators': 486}. Best is trial 57 with value: 0.6706897961401909.
[I 2025-12-15 22:43:08,863] Trial 72 finished with value: 0.6705098628737677 and parameters: {'max_depth': 3, 'learning_rate': 0.19261341067938853, 'n_estimators': 500}. Best is trial 57 with value: 0.6706897961401909.
[I 2025-12-15 22:43:09,485] Trial 73 finished with value: 0.6699462657355303 and parameters: {'max_depth': 4, 'learning_rate': 0.17926669746128227, 'n_estimators': 498}. Best is trial 57 with value: 0.6706897961401909.
[I 2025-12-15 22:43:09,873] Trial 74 finished with value: 0.6587090480478046 and parameters: {'max_depth': 2, 'learning_rate': 0.1785463159391382, 'n_estimators': 500}. Best is trial 57 with value: 0.6706897961401909.
[I 2025-12-15 22:43:10,418] Trial 75 finished with value: 0.665819997537261 and parameters: {'max_depth': 4, 'learning_rate': 0.18947799017743489, 'n_estimators': 462}. Best is trial 57 with value: 0.6706897961401909.
[I 2025-12-15 22:43:10,827] Trial 76 finished with value: 0.6656655877101251 and parameters: {'max_depth': 3, 'learning_rate': 0.16070471278387988, 'n_estimators': 430}. Best is trial 57 with value: 0.6706897961401909.
[I 2025-12-15 22:43:11,288] Trial 77 finished with value: 0.6668529416595099 and parameters: {'max_depth': 3, 'learning_rate': 0.22014134661827092, 'n_estimators': 474}. Best is trial 57 with value: 0.6706897961401909.
[I 2025-12-15 22:43:11,634] Trial 78 finished with value: 0.6562983078048595 and parameters: {'max_depth': 2, 'learning_rate': 0.17980444102084459, 'n_estimators': 444}. Best is trial 57 with value: 0.6706897961401909.
[I 2025-12-15 22:43:12,206] Trial 79 finished with value: 0.6697862333904411 and parameters: {'max_depth': 4, 'learning_rate': 0.1452846393840637, 'n_estimators': 493}. Best is trial 57 with value: 0.6706897961401909.
[I 2025-12-15 22:43:12,767] Trial 80 finished with value: 0.6701592487463117 and parameters: {'max_depth': 4, 'learning_rate': 0.14514063960760873, 'n_estimators': 491}. Best is trial 57 with value: 0.6706897961401909.
[I 2025-12-15 22:43:13,339] Trial 81 finished with value: 0.6705728401516114 and parameters: {'max_depth': 4, 'learning_rate': 0.14308738370797217, 'n_estimators': 494}. Best is trial 57 with value: 0.6706897961401909.
[I 2025-12-15 22:43:13,910] Trial 82 finished with value: 0.6705980336011318 and parameters: {'max_depth': 4, 'learning_rate': 0.14332095120934288, 'n_estimators': 493}. Best is trial 57 with value: 0.6706897961401909.
[I 2025-12-15 22:43:14,550] Trial 83 finished with value: 0.6691021011438435 and parameters: {'max_depth': 4, 'learning_rate': 0.14250534731326336, 'n_estimators': 494}. Best is trial 57 with value: 0.6706897961401909.
[I 2025-12-15 22:43:15,133] Trial 84 finished with value: 0.669798278016937 and parameters: {'max_depth': 4, 'learning_rate': 0.15986601882932722, 'n_estimators': 499}. Best is trial 57 with value: 0.6706897961401909.
[I 2025-12-15 22:43:15,719] Trial 85 finished with value: 0.6702588421963804 and parameters: {'max_depth': 4, 'learning_rate': 0.1592866302704246, 'n_estimators': 500}. Best is trial 57 with value: 0.6706897961401909.
[I 2025-12-15 22:43:16,293] Trial 86 finished with value: 0.6679609457618411 and parameters: {'max_depth': 4, 'learning_rate': 0.16073958113188744, 'n_estimators': 499}. Best is trial 57 with value: 0.6706897961401909.
[I 2025-12-15 22:43:16,994] Trial 87 finished with value: 0.6698324573416516 and parameters: {'max_depth': 5, 'learning_rate': 0.11977535150367166, 'n_estimators': 455}. Best is trial 57 with value: 0.6706897961401909.
[I 2025-12-15 22:43:17,668] Trial 88 finished with value: 0.6671411750290854 and parameters: {'max_depth': 5, 'learning_rate': 0.1240853587871179, 'n_estimators': 450}. Best is trial 57 with value: 0.6706897961401909.

Thời gian chạy tìm kiếm siêu tham số: 122.43 Giây
Siêu tham số tối ưu: {'max_depth': 5, 'learning_rate': 0.10131957052740347, 'n_estimators': 500}
AUC: 0.6712393179456736
Accuracy: 0.7130284230269802
Precision: 0.5038033937975425
Recall: 0.2157354046604861
F1 Score: 0.3021052631578947
Matthews Correlation Coefficient: 0.17880279873167124

Ma trận nhầm lẫn:
[[9023  848]
 [3130  861]]

Báo cáo phân loại:
              precision    recall  f1-score   support

           0       0.74      0.91      0.82      9871
           1       0.50      0.22      0.30      3991

    accuracy                           0.71     13862
   macro avg       0.62      0.56      0.56     13862
weighted avg       0.67      0.71      0.67     13862

Toàn bộ thời gian chạy: 123.54 Giây

## SHAP Values

In [7]:
import numpy as np
import shap
explainer = shap.Explainer(best_model)
shap_values = explainer.shap_values(X_train)


#Get shap value summary
shap_values
result = [np.mean([abs(items[i]) for items in shap_values]) for i in range(len(shap_values[0]))]

#Get column name
X.columns
result
# DataFrame
df_ = pd.DataFrame({'Feature': X.columns, 'mean|shap value|': result})
sorted_df = df_.sort_values(by='mean|shap value|',ascending=False)
# DataFrame
display(sorted_df)
sorted_df.to_csv("shap_values_sorted.csv", index=False)

     Feature  mean|shap value|
26   eqpdays          0.375417
1        mou          0.255777
21    months          0.248649
6    changem          0.183162
63   setprcm          0.175529
..       ...               ...
51  mailflag          0.001144
62    mcycle          0.000893
19  callfwdv          0.000607
43   occhmkr          0.000311
65   retcall          0.000121

[66 rows x 2 columns]

In [8]:
profit_table = {
    "eqpdays": 0.3922971,
    "mou": 0.27383575,
    "months": 0.2683537,
    "changem": 0.19033928,
    "phones": 0.15566355,
    "setprcm": 0.15500288,
    "overage": 0.12510847,
    "ownrent": 0.12364982,
    "creditaa": 0.111818574,
    "recchrge": 0.11178479,
    "directas": 0.10951055,
    "creditcd": 0.108519934,
    "dropvce": 0.0966647,
    "income": 0.095517606,
    "threeway": 0.09034747,
    "mailres": 0.08870609,
    "incmiss": 0.088341065,
    "prizmub": 0.081193425,
    "age1": 0.08063661,
    "blckvce": 0.07955432,
    "age2": 0.078548335,
    "uniqsubs": 0.07630953,
    "webcap": 0.075054586,
    "roam": 0.0738571,
    "models": 0.06989823,
    "peakvce": 0.06980787,
    "setprc": 0.06712751,
    "mourec": 0.066761546,
    "actvsubs": 0.064068116,
    "credita": 0.05903869,
    "opeakvce": 0.058492433,
    "revenue": 0.057051297,
    "changer": 0.052262787,
    "incalls": 0.05091391,
    "marryun": 0.050451566,
    "marryyes": 0.04999858,
    "callwait": 0.045237325,
    "newcelly": 0.044960454,
    "custcare": 0.04222929,
    "outcalls": 0.041492436,
    "retcalls": 0.03418307,
    "unansvce": 0.032022763,
    "prizmtwn": 0.030589614,
    "occprof": 0.030486966,
    "refurb": 0.027565725,
    "dropblk": 0.026701743,
    "truck": 0.022587338,
    "newcelln": 0.020809047,
    "prizmrur": 0.015735166,
    "refer": 0.013898367,
    "mailord": 0.013114,
    "pcown": 0.012731194,
    "occcrft": 0.010717165,
    "children": 0.009005423,
    "travel": 0.006408993,
    "occself": 0.0037108439,
    "rv": 0.0026592917,
    "occcler": 0.0024751162,
    "occret": 0.0019850743,
    "occstud": 0.0019252233,
    "retaccpt": 0.0018356557,
    "mailflag": 0.0014303686,
    "callfwdv": 0.00080224825,
    "mcycle": 0.0007587086,
    "occhmkr": 0.00045569523,
    "retcall": 0.0
}

# HAFCP Model For Training Dataset

## Highly Associated Fuzzy Churn Patterns in Binary Classification

### Fuzzy Triangle & Gaussion

In [ ]:
X_temp=pd.concat([X_train,y_train],axis=1)

# Lấy ra các row nhãn là churn
X_churn_label = X_temp[X_temp['churn'] == 1]

X_churn_label

,revenue,mou,recchrge,directas,overage,roam,changem,changer,dropvce,blckvce,...,newcelly,newcelln,refer,incmiss,income,mcycle,setprcm,setprc,retcall,churn
52253,26.040001,44.25,24.990000,0.0000,0.00,0.0000,-31.25,-1.050000,0.000000,0.000000,...,1,0,0,0,5,0,1,0.00000,0,1
63241,48.867500,295.25,39.990002,0.4950,51.75,0.0000,-98.25,-17.887501,4.000000,0.000000,...,0,0,1,0,6,0,1,0.00000,0,1
67661,39.237499,37.75,44.990002,0.2475,0.00,0.0000,-4.75,-0.247500,0.333333,4.333333,...,0,0,0,0,9,0,1,0.00000,0,1
53577,111.422501,1220.00,59.990002,2.7225,171.00,4.1950,31.00,-29.882500,19.666666,1.666667,...,0,0,0,0,6,0,0,29.98999,0,1
52347,30.272499,78.25,30.000000,0.2475,0.00,0.0000,-60.25,-0.272500,0.333333,3.333333,...,0,0,0,0,4,1,0,29.98999,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61120,97.562500,832.50,49.990002,0.2475,90.50,1.5725,484.50,46.817501,3.333333,0.000000,...,1,0,0,0,8,0,0,149.98999,0,1
66341,84.989998,371.25,94.989998,0.0000,0.00,0.0000,-105.25,0.000000,0.000000,2.000000,...,0,0,0,1,0,0,0,79.98999,0,1
68840,10.097500,75.75,10.000000,0.0000,0.25,0.0000,-42.75,-0.097500,0.000000,0.333333,...,0,0,0,0,4,0,1,0.00000,0,1
61658,99.055000,837.25,59.990002,3.2175,92.75,0.0000,-354.25,-49.064999,2.666667,14.666667,...,0,1,0,0,9,0,0,199.98999,0,1
56165,78.925003,641.75,75.000000,0.0000,0.00,0.0000,15.25,-0.675000,2.666667,0.666667,...,0,1,0,0,6,0,0,149.98999,0,1

In [ ]:
def print_column_names(X_churn_label):
    print("Các cột trong DataFrame là:")
    print(list(X_churn_label.columns))
print_column_names(X_churn_label)

Các cột trong DataFrame là:
['revenue', 'mou', 'recchrge', 'directas', 'overage', 'roam', 'changem', 'changer', 'dropvce', 'blckvce', 'unansvce', 'custcare', 'threeway', 'mourec', 'outcalls', 'incalls', 'peakvce', 'opeakvce', 'dropblk', 'callfwdv', 'callwait', 'months', 'uniqsubs', 'actvsubs', 'phones', 'models', 'eqpdays', 'age1', 'age2', 'children', 'credita', 'creditaa', 'prizmrur', 'prizmub', 'prizmtwn', 'refurb', 'webcap', 'truck', 'rv', 'occprof', 'occcler', 'occcrft', 'occstud', 'occhmkr', 'occret', 'occself', 'ownrent', 'marryun', 'marryyes', 'mailord', 'mailres', 'mailflag', 'travel', 'pcown', 'creditcd', 'retcalls', 'retaccpt', 'newcelly', 'newcelln', 'refer', 'incmiss', 'income', 'mcycle', 'setprcm', 'setprc', 'retcall', 'churn']

In [ ]:
X_churn_label.shape

(15993, 67)

In [ ]:
Xtofuzzy_Tri  = X_churn_label[['revenue', 'mou', 'recchrge', 'directas', 'overage', 'roam', 'changem', 'changer', 'dropvce', 'blckvce', 'unansvce', 'custcare', 'threeway', 'mourec', 'outcalls', 'incalls', 'peakvce', 'opeakvce', 'dropblk', 'callfwdv', 'callwait', 'months', 'uniqsubs', 'actvsubs', 'phones', 'models', 'eqpdays', 'age1', 'age2', 'children', 'credita', 'creditaa', 'prizmrur', 'prizmub', 'prizmtwn', 'refurb', 'webcap', 'truck', 'rv', 'occprof', 'occcler', 'occcrft', 'occstud', 'occhmkr', 'occret', 'occself', 'ownrent', 'marryun', 'marryyes', 'mailord', 'mailres', 'mailflag', 'travel', 'pcown', 'creditcd', 'retcalls', 'retaccpt', 'newcelly', 'newcelln', 'refer', 'incmiss', 'income', 'mcycle', 'setprcm', 'setprc', 'retcall']]

In [ ]:
import pandas as pd

# Membership function
def triangular_mf(x, a, b, c):
    if x <= a:
        return 0
    elif a < x <= b:
        return (x - a) / (b - a)
    elif b < x <= c:
        return (c - x) / (c - b)
    else:
        return 0

# Maximal cardinality
def fuzzy_classification(x, min_val, median_val, max_val):
    low_membership = triangular_mf(x, min_val, min_val, median_val)
    medium_membership = triangular_mf(x, min_val, median_val, max_val)
    high_membership = triangular_mf(x, median_val, max_val, max_val)

    max_membership = max(low_membership, medium_membership, high_membership)

    if max_membership == low_membership:
        return 0
    elif max_membership == medium_membership:
        return 1
    else:
        return 2


fuzzy_df = pd.DataFrame()
# For each feature
for feature in Xtofuzzy_Tri.columns:
    min_val = Xtofuzzy_Tri[feature].min()
    median_val = Xtofuzzy_Tri[feature].quantile(0.5)
    max_val = Xtofuzzy_Tri[feature].max()

    fuzzy_df[f'{feature}_fuzzy'] = Xtofuzzy_Tri[feature].apply(lambda x: fuzzy_classification(x, min_val, median_val, max_val))

fuzzy_df

# Define a dict
boundaries = {}

for feature in Xtofuzzy_Tri.columns:
    min_val = Xtofuzzy_Tri[feature].min()
    median_val = Xtofuzzy_Tri[feature].quantile(0.5)
    max_val = Xtofuzzy_Tri[feature].max()

    # Save
    boundaries[feature] = (min_val, median_val, max_val)

# print out
for feature, bounds in boundaries.items():
    print(f"Feature: {feature}")
    print(f"Low boundary: {bounds[0]}, Medium boundary: {bounds[1]}, High boundary: {bounds[2]}")
    print("------")

fuzzy_df

Feature: revenue
Low boundary: 3.75, Medium boundary: 47.62749863, High boundary: 861.1049805
------
Feature: mou
Low boundary: 0.0, Medium boundary: 330.0, High boundary: 5409.75
------
Feature: recchrge
Low boundary: -6.050000191, Medium boundary: 44.26250076, High boundary: 337.9750061
------
Feature: directas
Low boundary: 0.0, Medium boundary: 0.247500002, High boundary: 46.52999878
------
Feature: overage
Low boundary: 0.0, Medium boundary: 3.75, High boundary: 2018.0
------
Feature: roam
Low boundary: 0.0, Medium boundary: 0.0, High boundary: 850.8624878
------
Feature: changem
Low boundary: -2867.5, Medium boundary: -10.25, High boundary: 5192.25
------
Feature: changer
Low boundary: -851.1049805, Medium boundary: -0.310000002, High boundary: 2483.482422
------
Feature: dropvce
Low boundary: 0.0, Medium boundary: 3.0, High boundary: 208.6666718
------
Feature: blckvce
Low boundary: 0.0, Medium boundary: 1.0, High boundary: 314.6666565
------
Feature: unansvce
Low boundary: 0.0, Medium boundary: 15.0, High boundary: 771.333313
------
Feature: custcare
Low boundary: 0.0, Medium boundary: 0.0, High boundary: 172.3333282
------
Feature: threeway
Low boundary: 0.0, Medium boundary: 0.0, High boundary: 30.0
------
Feature: mourec
Low boundary: 0.0, Medium boundary: 45.88999939, High boundary: 2075.893311
------
Feature: outcalls
Low boundary: 0.0, Medium boundary: 12.33333302, High boundary: 517.0
------
Feature: incalls
Low boundary: 0.0, Medium boundary: 1.666666627, High boundary: 282.0
------
Feature: peakvce
Low boundary: 0.0, Medium boundary: 57.66666794, High boundary: 1257.0
------
Feature: opeakvce
Low boundary: 0.0, Medium boundary: 32.0, High boundary: 1438.333374
------
Feature: dropblk
Low boundary: 0.0, Medium boundary: 5.333333492, High boundary: 328.6666565
------
Feature: callfwdv
Low boundary: 0.0, Medium boundary: 0.0, High boundary: 26.33333397
------
Feature: callwait
Low boundary: 0.0, Medium boundary: 0.0, High boundary: 195.0
------
Feature: months
Low boundary: 6, Medium boundary: 17.0, High boundary: 61
------
Feature: uniqsubs
Low boundary: 1, Medium boundary: 1.0, High boundary: 196
------
Feature: actvsubs
Low boundary: 0, Medium boundary: 1.0, High boundary: 53
------
Feature: phones
Low boundary: 1.0, Medium boundary: 1.0, High boundary: 22.0
------
Feature: models
Low boundary: 1.0, Medium boundary: 1.0, High boundary: 14.0
------
Feature: eqpdays
Low boundary: -4.0, Medium boundary: 366.0, High boundary: 1698.0
------
Feature: age1
Low boundary: 0.0, Medium boundary: 34.0, High boundary: 98.0
------
Feature: age2
Low boundary: 0.0, Medium boundary: 0.0, High boundary: 99.0
------
Feature: children
Low boundary: 0, Medium boundary: 0.0, High boundary: 1
------
Feature: credita
Low boundary: 0, Medium boundary: 0.0, High boundary: 1
------
Feature: creditaa
Low boundary: 0, Medium boundary: 0.0, High boundary: 1
------
Feature: prizmrur
Low boundary: 0, Medium boundary: 0.0, High boundary: 1
------
Feature: prizmub
Low boundary: 0, Medium boundary: 0.0, High boundary: 1
------
Feature: prizmtwn
Low boundary: 0, Medium boundary: 0.0, High boundary: 1
------
Feature: refurb
Low boundary: 0, Medium boundary: 0.0, High boundary: 1
------
Feature: webcap
Low boundary: 0, Medium boundary: 1.0, High boundary: 1
------
Feature: truck
Low boundary: 0, Medium boundary: 0.0, High boundary: 1
------
Feature: rv
Low boundary: 0, Medium boundary: 0.0, High boundary: 1
------
Feature: occprof
Low boundary: 0, Medium boundary: 0.0, High boundary: 1
------
Feature: occcler
Low boundary: 0, Medium boundary: 0.0, High boundary: 1
------
Feature: occcrft
Low boundary: 0, Medium boundary: 0.0, High boundary: 1
------
Feature: occstud
Low boundary: 0, Medium boundary: 0.0, High boundary: 1
------
Feature: occhmkr
Low boundary: 0, Medium boundary: 0.0, High boundary: 1
------
Feature: occret
Low boundary: 0, Medium boundary: 0.0, High boundary: 1
------
Feature: occself
Low boundary: 0, Medium boundary: 0.0, High boundary: 1
------
Feature: ownrent
Low boundary: 0, Medium boundary: 0.0, High boundary: 1
------
Feature: marryun
Low boundary: 0, Medium boundary: 0.0, High boundary: 1
------
Feature: marryyes
Low boundary: 0, Medium boundary: 0.0, High boundary: 1
------
Feature: mailord
Low boundary: 0, Medium boundary: 0.0, High boundary: 1
------
Feature: mailres
Low boundary: 0, Medium boundary: 0.0, High boundary: 1
------
Feature: mailflag
Low boundary: 0, Medium boundary: 0.0, High boundary: 1
------
Feature: travel
Low boundary: 0, Medium boundary: 0.0, High boundary: 1
------
Feature: pcown
Low boundary: 0, Medium boundary: 0.0, High boundary: 1
------
Feature: creditcd
Low boundary: 0, Medium boundary: 1.0, High boundary: 1
------
Feature: retcalls
Low boundary: 0, Medium boundary: 0.0, High boundary: 4
------
Feature: retaccpt
Low boundary: 0, Medium boundary: 0.0, High boundary: 4
------
Feature: newcelly
Low boundary: 0, Medium boundary: 0.0, High boundary: 1
------
Feature: newcelln
Low boundary: 0, Medium boundary: 0.0, High boundary: 1
------
Feature: refer
Low boundary: 0, Medium boundary: 0.0, High boundary: 9
------
Feature: incmiss
Low boundary: 0, Medium boundary: 0.0, High boundary: 1
------
Feature: income
Low boundary: 0, Medium boundary: 5.0, High boundary: 9
------
Feature: mcycle
Low boundary: 0, Medium boundary: 0.0, High boundary: 1
------
Feature: setprcm
Low boundary: 0, Medium boundary: 1.0, High boundary: 1
------
Feature: setprc
Low boundary: 0.0, Medium boundary: 0.0, High boundary: 499.9899902
------
Feature: retcall
Low boundary: 0, Medium boundary: 0.0, High boundary: 1
------

,revenue_fuzzy,mou_fuzzy,recchrge_fuzzy,directas_fuzzy,overage_fuzzy,roam_fuzzy,changem_fuzzy,changer_fuzzy,dropvce_fuzzy,blckvce_fuzzy,...,retaccpt_fuzzy,newcelly_fuzzy,newcelln_fuzzy,refer_fuzzy,incmiss_fuzzy,income_fuzzy,mcycle_fuzzy,setprcm_fuzzy,setprc_fuzzy,retcall_fuzzy
52253,1,0,1,0,0,0,1,1,0,0,...,0,2,0,0,0,1,0,1,0,0
63241,1,1,1,1,1,0,1,1,1,0,...,0,0,0,1,0,1,0,1,0,0
67661,1,0,1,1,0,0,1,1,0,1,...,0,0,0,0,0,2,0,1,0,0
53577,1,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,1,0,0,1,0
52347,1,0,1,1,0,0,1,1,0,1,...,0,0,0,0,0,1,2,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61120,1,1,1,1,1,1,1,1,1,0,...,0,2,0,0,0,2,0,0,1,0
66341,1,1,1,0,0,0,1,1,0,1,...,0,0,0,0,2,0,0,0,1,0
68840,0,0,0,0,0,0,1,1,0,0,...,0,0,0,0,0,1,0,1,0,0
61658,1,1,1,1,1,0,1,1,1,1,...,0,0,2,0,0,2,0,0,1,0
56165,1,1,1,0,0,0,1,1,1,1,...,0,0,2,0,0,1,0,0,1,0

In [ ]:

df_encoded = fuzzy_df
fuzzy_columns = [col for col in df_encoded.columns]

# one-hot encoding
df_encoded = pd.get_dummies(df_encoded, columns=fuzzy_columns)

for col in fuzzy_columns:
    mappings = {
        f"{col}_{i}": f"{col}_{i}" for i in range(3)
    }
    df_encoded.rename(columns=mappings, inplace=True)
df_encoded.columns

Index(['revenue_fuzzy_0', 'revenue_fuzzy_1', 'revenue_fuzzy_2', 'mou_fuzzy_0',
       'mou_fuzzy_1', 'mou_fuzzy_2', 'recchrge_fuzzy_0', 'recchrge_fuzzy_1',
       'recchrge_fuzzy_2', 'directas_fuzzy_0',
       ...
       'income_fuzzy_2', 'mcycle_fuzzy_0', 'mcycle_fuzzy_2', 'setprcm_fuzzy_0',
       'setprcm_fuzzy_1', 'setprc_fuzzy_0', 'setprc_fuzzy_1', 'setprc_fuzzy_2',
       'retcall_fuzzy_0', 'retcall_fuzzy_2'],
      dtype='object', length=166)

In [ ]:
dataset = {}

transaction_id = 1
for _, row in df_encoded.iterrows():
    transaction = {}
    for column, value in row.items():
        transaction[column] = value
    transaction_key = f'transaction{transaction_id}'
    dataset[transaction_key] = transaction
    transaction_id += 1

In [ ]:
transactions = dataset

filtered_transactions = {transaction: {key: value for key, value in items.items() if value != 0}
                        for transaction, items in transactions.items()}

filtered_transactions

{'transaction1': {'revenue_fuzzy_1': True,
  'mou_fuzzy_0': True,
  'recchrge_fuzzy_1': True,
  'directas_fuzzy_0': True,
  'overage_fuzzy_0': True,
  'roam_fuzzy_0': True,
  'changem_fuzzy_1': True,
  'changer_fuzzy_1': True,
  'dropvce_fuzzy_0': True,
  'blckvce_fuzzy_0': True,
  'unansvce_fuzzy_0': True,
  'custcare_fuzzy_0': True,
  'threeway_fuzzy_0': True,
  'mourec_fuzzy_0': True,
  'outcalls_fuzzy_1': True,
  'incalls_fuzzy_1': True,
  'peakvce_fuzzy_0': True,
  'opeakvce_fuzzy_0': True,
  'dropblk_fuzzy_0': True,
  'callfwdv_fuzzy_0': True,
  'callwait_fuzzy_0': True,
  'months_fuzzy_1': True,
  'uniqsubs_fuzzy_0': True,
  'actvsubs_fuzzy_1': True,
  'phones_fuzzy_0': True,
  'models_fuzzy_0': True,
  'eqpdays_fuzzy_1': True,
  'age1_fuzzy_1': True,
  'age2_fuzzy_1': True,
  'children_fuzzy_2': True,
  'credita_fuzzy_0': True,
  'creditaa_fuzzy_0': True,
  'prizmrur_fuzzy_0': True,
  'prizmub_fuzzy_0': True,
  'prizmtwn_fuzzy_0': True,
  'refurb_fuzzy_0': True,
  'webcap_fuzzy_0': True,
  'truck_fuzzy_0': True,
  'rv_fuzzy_0': True,
  'occprof_fuzzy_0': True,
  'occcler_fuzzy_0': True,
  'occcrft_fuzzy_0': True,
  'occstud_fuzzy_0': True,
  'occhmkr_fuzzy_0': True,
  'occret_fuzzy_0': True,
  'occself_fuzzy_0': True,
  'ownrent_fuzzy_0': True,
  'marryun_fuzzy_0': True,
  'marryyes_fuzzy_2': True,
  'mailord_fuzzy_0': True,
  'mailres_fuzzy_0': True,
  'mailflag_fuzzy_0': True,
  'travel_fuzzy_0': True,
  'pcown_fuzzy_0': True,
  'creditcd_fuzzy_1': True,
  'retcalls_fuzzy_0': True,
  'retaccpt_fuzzy_0': True,
  'newcelly_fuzzy_2': True,
  'newcelln_fuzzy_0': True,
  'refer_fuzzy_0': True,
  'incmiss_fuzzy_0': True,
  'income_fuzzy_1': True,
  'mcycle_fuzzy_0': True,
  'setprcm_fuzzy_1': True,
  'setprc_fuzzy_0': True,
  'retcall_fuzzy_0': True},
 'transaction2': {'revenue_fuzzy_1': True,
  'mou_fuzzy_1': True,
  'recchrge_fuzzy_1': True,
  'directas_fuzzy_1': True,
  'overage_fuzzy_1': True,
  'roam_fuzzy_0': True,
  'changem_fuzzy_1': True,
  'changer_fuzzy_1': True,
  'dropvce_fuzzy_1': True,
  'blckvce_fuzzy_0': True,
  'unansvce_fuzzy_1': True,
  'custcare_fuzzy_1': True,
  'threeway_fuzzy_0': True,
  'mourec_fuzzy_1': True,
  'outcalls_fuzzy_1': True,
  'incalls_fuzzy_1': True,
  'peakvce_fuzzy_1': True,
  'opeakvce_fuzzy_1': True,
  'dropblk_fuzzy_1': True,
  'callfwdv_fuzzy_0': True,
  'callwait_fuzzy_1': True,
  'months_fuzzy_0': True,
  'uniqsubs_fuzzy_0': True,
  'actvsubs_fuzzy_1': True,
  'phones_fuzzy_0': True,
  'models_fuzzy_0': True,
  'eqpdays_fuzzy_1': True,
  'age1_fuzzy_1': True,
  'age2_fuzzy_1': True,
  'children_fuzzy_0': True,
  'credita_fuzzy_0': True,
  'creditaa_fuzzy_0': True,
  'prizmrur_fuzzy_0': True,
  'prizmub_fuzzy_0': True,
  'prizmtwn_fuzzy_0': True,
  'refurb_fuzzy_0': True,
  'webcap_fuzzy_1': True,
  'truck_fuzzy_0': True,
  'rv_fuzzy_0': True,
  'occprof_fuzzy_0': True,
  'occcler_fuzzy_0': True,
  'occcrft_fuzzy_0': True,
  'occstud_fuzzy_0': True,
  'occhmkr_fuzzy_0': True,
  'occret_fuzzy_0': True,
  'occself_fuzzy_0': True,
  'ownrent_fuzzy_0': True,
  'marryun_fuzzy_0': True,
  'marryyes_fuzzy_2': True,
  'mailord_fuzzy_0': True,
  'mailres_fuzzy_0': True,
  'mailflag_fuzzy_0': True,
  'travel_fuzzy_0': True,
  'pcown_fuzzy_0': True,
  'creditcd_fuzzy_1': True,
  'retcalls_fuzzy_0': True,
  'retaccpt_fuzzy_0': True,
  'newcelly_fuzzy_0': True,
  'newcelln_fuzzy_0': True,
  'refer_fuzzy_1': True,
  'incmiss_fuzzy_0': True,
  'income_fuzzy_1': True,
  'mcycle_fuzzy_0': True,
  'setprcm_fuzzy_1': True,
  'setprc_fuzzy_0': True,
  'retcall_fuzzy_0': True},
 'transaction3': {'revenue_fuzzy_1': True,
  'mou_fuzzy_0': True,
  'recchrge_fuzzy_1': True,
  'directas_fuzzy_1': True,
  'overage_fuzzy_0': True,
  'roam_fuzzy_0': True,
  'changem_fuzzy_1': True,
  'changer_fuzzy_1': True,
  'dropvce_fuzzy_0': True,
  'blckvce_fuzzy_1': True,
  'unansvce_fuzzy_0': True,
  'custcare_fuzzy_0': True,
  'threeway_fuzzy_0': True,
  'mourec_fuzzy_0': True,
  'outcalls_fuzzy_0': True,
  'incalls_fuzzy_0': True,
  'peakvce_fuzzy_0': True,
  'opeakvce_fuzzy_0': True,
  'dropblk_fuzzy_1': True,
  'callfwdv_fuzzy_0': True,
  'callwait_fuzzy_0': True,
  'months_fuzzy_0': True,
  'uniqsubs_fuzzy_0': True,
  'actvsubs_fuzzy_1': True,
  'phones_fuzzy_0': True,
  'models_fuzzy_0': True,
  'eqpdays_fuzzy_1': True,
  'age1_fuzzy_1': True,
  'age2_fuzzy_2': True,
  'children_fuzzy_0': True,
  'credita_fuzzy_0': True,
  'creditaa_fuzzy_0': True,
  'prizmrur_fuzzy_0': True,
  'prizmub_fuzzy_2': True,
  'prizmtwn_fuzzy_0': True,
  'refurb_fuzzy_0': True,
  'webcap_fuzzy_1': True,
  'truck_fuzzy_0': True,
  'rv_fuzzy_0': True,
  'occprof_fuzzy_2': True,
  'occcler_fuzzy_0': True,
  'occcrft_fuzzy_0': True,
  'occstud_fuzzy_0': True,
  'occhmkr_fuzzy_0': True,
  'occret_fuzzy_0': True,
  'occself_fuzzy_0': True,
  'ownrent_fuzzy_0': True,
  'marryun_fuzzy_0': True,
  'marryyes_fuzzy_2': True,
  'mailord_fuzzy_2': True,
  'mailres_fuzzy_2': True,
  'mailflag_fuzzy_0': True,
  'travel_fuzzy_0': True,
  'pcown_fuzzy_0': True,
  'creditcd_fuzzy_1': True,
  'retcalls_fuzzy_0': True,
  'retaccpt_fuzzy_0': True,
  'newcelly_fuzzy_0': True,
  'newcelln_fuzzy_0': True,
  'refer_fuzzy_0': True,
  'incmiss_fuzzy_0': True,
  'income_fuzzy_2': True,
  'mcycle_fuzzy_0': True,
  'setprcm_fuzzy_1': True,
  'setprc_fuzzy_0': True,
  'retcall_fuzzy_0': True},
 'transaction4': {'revenue_fuzzy_1': True,
  'mou_fuzzy_1': True,
  'recchrge_fuzzy_1': True,
  'directas_fuzzy_1': True,
  'overage_fuzzy_1': True,
  'roam_fuzzy_1': True,
  'changem_fuzzy_1': True,
  'changer_fuzzy_1': True,
  'dropvce_fuzzy_1': True,
  'blckvce_fuzzy_1': True,
  'unansvce_fuzzy_1': True,
  'custcare_fuzzy_1': True,
  'threeway_fuzzy_1': True,
  'mourec_fuzzy_1': True,
  'outcalls_fuzzy_1': True,
  'incalls_fuzzy_0': True,
  'peakvce_fuzzy_1': True,
  'opeakvce_fuzzy_1': True,
  'dropblk_fuzzy_1': True,
  'callfwdv_fuzzy_0': True,
  'callwait_fuzzy_0': True,
  'months_fuzzy_1': True,
  'uniqsubs_fuzzy_0': True,
  'actvsubs_fuzzy_1': True,
  'phones_fuzzy_1': True,
  'models_fuzzy_1': True,
  'eqpdays_fuzzy_0': True,
  'age1_fuzzy_1': True,
  'age2_fuzzy_0': True,
  'children_fuzzy_0': True,
  'credita_fuzzy_2': True,
  'creditaa_fuzzy_0': True,
  'prizmrur_fuzzy_0': True,
  'prizmub_fuzzy_2': True,
  'prizmtwn_fuzzy_0': True,
  'refurb_fuzzy_0': True,
  'webcap_fuzzy_1': True,
  'truck_fuzzy_0': True,
  'rv_fuzzy_0': True,
  'occprof_fuzzy_0': True,
  'occcler_fuzzy_0': True,
  'occcrft_fuzzy_0': True,
  'occstud_fuzzy_0': True,
  'occhmkr_fuzzy_0': True,
  'occret_fuzzy_0': True,
  'occself_fuzzy_0': True,
  'ownrent_fuzzy_2': True,
  'marryun_fuzzy_0': True,
  'marryyes_fuzzy_2': True,
  'mailord_fuzzy_0': True,
  'mailres_fuzzy_0': True,
  'mailflag_fuzzy_0': True,
  'travel_fuzzy_0': True,
  'pcown_fuzzy_0': True,
  'creditcd_fuzzy_1': True,
  'retcalls_fuzzy_0': True,
  'retaccpt_fuzzy_0': True,
  'newcelly_fuzzy_0': True,
  'newcelln_fuzzy_0': True,
  'refer_fuzzy_0': True,
  'incmiss_fuzzy_0': True,
  'income_fuzzy_1': True,
  'mcycle_fuzzy_0': True,
  'setprcm_fuzzy_0': True,
  'setprc_fuzzy_1': True,
  'retcall_fuzzy_0': True},
 'transaction5': {'revenue_fuzzy_1': True,
  'mou_fuzzy_0': True,
  'recchrge_fuzzy_1': True,
  'directas_fuzzy_1': True,
  'overage_fuzzy_0': True,
  'roam_fuzzy_0': True,
  'changem_fuzzy_1': True,
  'changer_fuzzy_1': True,
  'dropvce_fuzzy_0': True,
  'blckvce_fuzzy_1': True,
  'unansvce_fuzzy_0': True,
  'custcare_fuzzy_0': True,
  'threeway_fuzzy_0': True,
  'mourec_fuzzy_0': True,
  'outcalls_fuzzy_0': True,
  'incalls_fuzzy_0': True,
  'peakvce_fuzzy_0': True,
  'opeakvce_fuzzy_0': True,
  'dropblk_fuzzy_1': True,
  'callfwdv_fuzzy_0': True,
  'callwait_fuzzy_0': True,
  'months_fuzzy_1': True,
  'uniqsubs_fuzzy_0': True,
  'actvsubs_fuzzy_1': True,
  'phones_fuzzy_1': True,
  'models_fuzzy_1': True,
  'eqpdays_fuzzy_1': True,
  'age1_fuzzy_1': True,
  'age2_fuzzy_0': True,
  'children_fuzzy_0': True,
  'credita_fuzzy_0': True,
  'creditaa_fuzzy_0': True,
  'prizmrur_fuzzy_0': True,
  'prizmub_fuzzy_0': True,
  'prizmtwn_fuzzy_0': True,
  'refurb_fuzzy_2': True,
  'webcap_fuzzy_1': True,
  'truck_fuzzy_2': True,
  'rv_fuzzy_0': True,
  'occprof_fuzzy_0': True,
  'occcler_fuzzy_0': True,
  'occcrft_fuzzy_0': True,
  'occstud_fuzzy_0': True,
  'occhmkr_fuzzy_0': True,
  'occret_fuzzy_0': True,
  'occself_fuzzy_0': True,
  'ownrent_fuzzy_0': True,
  'marryun_fuzzy_0': True,
  'marryyes_fuzzy_0': True,
  'mailord_fuzzy_0': True,
  'mailres_fuzzy_0': True,
  'mailflag_fuzzy_0': True,
  'travel_fuzzy_0': True,
  'pcown_fuzzy_0': True,
  'creditcd_fuzzy_1': True,
  'retcalls_fuzzy_0': True,
  'retaccpt_fuzzy_0': True,
  'newcelly_fuzzy_0': True,
  'newcelln_fuzzy_0': True,
  'refer_fuzzy_0': True,
  'incmiss_fuzzy_0': True,
  'income_fuzzy_1': True,
  'mcycle_fuzzy_2': True,
  'setprcm_fuzzy_0': True,
  'setprc_fuzzy_1': True,
  'retcall_fuzzy_0': True},
 'transaction6': {'revenue_fuzzy_1': True,
  'mou_fuzzy_1': True,
  'recchrge_fuzzy_1': True,
  'directas_fuzzy_1': True,
  'overage_fuzzy_1': True,
  'roam_fuzzy_0': True,
  'changem_fuzzy_1': True,
  'changer_fuzzy_1': True,
  'dropvce_fuzzy_1': True,
  'blckvce_fuzzy_1': True,
  'unansvce_fuzzy_1': True,
  'custcare_fuzzy_0': True,
  'threeway_fuzzy_0': True,
  'mourec_fuzzy_1': True,
  'outcalls_fuzzy_0': True,
  'incalls_fuzzy_1': True,
  'peakvce_fuzzy_1': True,
  'opeakvce_fuzzy_1': True,
  'dropblk_fuzzy_1': True,
  'callfwdv_fuzzy_0': True,
  'callwait_fuzzy_0': True,
  'months_fuzzy_1': True,
  'uniqsubs_fuzzy_0': True,
  'actvsubs_fuzzy_1': True,
  'phones_fuzzy_0': True,
  'models_fuzzy_0': True,
  'eqpdays_fuzzy_1': True,
  'age1_fuzzy_0': True,
  'age2_fuzzy_0': True,
  'children_fuzzy_0': True,
  'credita_fuzzy_0': True,
  'creditaa_fuzzy_0': True,
  'prizmrur_fuzzy_0': True,
  'prizmub_fuzzy_0': True,
  'prizmtwn_fuzzy_0': True,
  'refurb_fuzzy_0': True,
  'webcap_fuzzy_1': True,
  'truck_fuzzy_0': True,
  'rv_fuzzy_0': True,
  'occprof_fuzzy_0': True,
  'occcler_fuzzy_0': True,
  'occcrft_fuzzy_0': True,
  'occstud_fuzzy_0': True,
  'occhmkr_fuzzy_0': True,
  'occret_fuzzy_0': True,
  'occself_fuzzy_0': True,
  'ownrent_fuzzy_0': True,
  'marryun_fuzzy_2': True,
  'marryyes_fuzzy_0': True,
  'mailord_fuzzy_0': True,
  'mailres_fuzzy_0': True,
  'mailflag_fuzzy_0': True,
  'travel_fuzzy_0': True,
  'pcown_fuzzy_0': True,
  'creditcd_fuzzy_1': True,
  'retcalls_fuzzy_0': True,
  'retaccpt_fuzzy_0': True,
  'newcelly_fuzzy_0': True,
  'newcelln_fuzzy_0': True,
  'refer_fuzzy_0': True,
  'incmiss_fuzzy_0': True,
  'income_fuzzy_2': True,
  'mcycle_fuzzy_0': True,
  'setprcm_fuzzy_1': True,
  'setprc_fuzzy_0': True,
  'retcall_fuzzy_0': True},
 'transaction7': {'revenue_fuzzy_1': True,
  'mou_fuzzy_1': True,
  'recchrge_fuzzy_1': True,
  'directas_fuzzy_1': True,
  'overage_fuzzy_1': True,
  'roam_fuzzy_0': True,
  'changem_fuzzy_1': True,
  'changer_fuzzy_1': True,
  'dropvce_fuzzy_1': True,
  'blckvce_fuzzy_1': True,
  'unansvce_fuzzy_1': True,
  'custcare_fuzzy_1': True,
  'threeway_fuzzy_1': True,
  'mourec_fuzzy_1': True,
  'outcalls_fuzzy_1': True,
  'incalls_fuzzy_1': True,
  'peakvce_fuzzy_1': True,
  'opeakvce_fuzzy_1': True,
  'dropblk_fuzzy_1': True,
  'callfwdv_fuzzy_0': True,
  'callwait_fuzzy_1': True,
  'months_fuzzy_0': True,
  'uniqsubs_fuzzy_1': True,
  'actvsubs_fuzzy_1': True,
  'phones_fuzzy_1': True,
  'models_fuzzy_0': True,
  'eqpdays_fuzzy_1': True,
  'age1_fuzzy_1': True,
  'age2_fuzzy_0': True,
  'children_fuzzy_0': True,
  'credita_fuzzy_0': True,
  'creditaa_fuzzy_0': True,
  'prizmrur_fuzzy_0': True,
  'prizmub_fuzzy_0': True,
  'prizmtwn_fuzzy_0': True,
  'refurb_fuzzy_0': True,
  'webcap_fuzzy_1': True,
  'truck_fuzzy_0': True,
  'rv_fuzzy_0': True,
  'occprof_fuzzy_0': True,
  'occcler_fuzzy_0': True,
  'occcrft_fuzzy_0': True,
  'occstud_fuzzy_0': True,
  'occhmkr_fuzzy_0': True,
  'occret_fuzzy_0': True,
  'occself_fuzzy_0': True,
  'ownrent_fuzzy_2': True,
  'marryun_fuzzy_0': True,
  'marryyes_fuzzy_0': True,
  'mailord_fuzzy_0': True,
  'mailres_fuzzy_0': True,
  'mailflag_fuzzy_0': True,
  'travel_fuzzy_0': True,
  'pcown_fuzzy_0': True,
  'creditcd_fuzzy_1': True,
  'retcalls_fuzzy_0': True,
  'retaccpt_fuzzy_0': True,
  'newcelly_fuzzy_0': True,
  'newcelln_fuzzy_0': True,
  'refer_fuzzy_0': True,
  'incmiss_fuzzy_0': True,
  'income_fuzzy_1': True,
  'mcycle_fuzzy_0': True,
  'setprcm_fuzzy_0': True,
  'setprc_fuzzy_1': True,
  'retcall_fuzzy_0': True},
 'transaction8': {'revenue_fuzzy_1': True,
  'mou_fuzzy_0': True,
  'recchrge_fuzzy_1': True,
  'directas_fuzzy_0': True,
  'overage_fuzzy_0': True,
  'roam_fuzzy_0': True,
  'changem_fuzzy_1': True,
  'changer_fuzzy_1': True,
  'dropvce_fuzzy_1': True,
  'blckvce_fuzzy_0': True,
  'unansvce_fuzzy_0': True,
  'custcare_fuzzy_0': True,
  'threeway_fuzzy_0': True,
  'mourec_fuzzy_0': True,
  'outcalls_fuzzy_0': True,
  'incalls_fuzzy_0': True,
  'peakvce_fuzzy_0': True,
  'opeakvce_fuzzy_0': True,
  'dropblk_fuzzy_0': True,
  'callfwdv_fuzzy_0': True,
  'callwait_fuzzy_0': True,
  'months_fuzzy_1': True,
  'uniqsubs_fuzzy_0': True,
  'actvsubs_fuzzy_1': True,
  'phones_fuzzy_0': True,
  'models_fuzzy_0': True,
  'eqpdays_fuzzy_1': True,
  'age1_fuzzy_0': True,
  'age2_fuzzy_0': True,
  'children_fuzzy_0': True,
  'credita_fuzzy_0': True,
  'creditaa_fuzzy_2': True,
  'prizmrur_fuzzy_0': True,
  'prizmub_fuzzy_2': True,
  'prizmtwn_fuzzy_0': True,
  'refurb_fuzzy_0': True,
  'webcap_fuzzy_1': True,
  'truck_fuzzy_2': True,
  'rv_fuzzy_2': True,
  'occprof_fuzzy_0': True,
  'occcler_fuzzy_0': True,
  'occcrft_fuzzy_0': True,
  'occstud_fuzzy_0': True,
  'occhmkr_fuzzy_0': True,
  'occret_fuzzy_0': True,
  'occself_fuzzy_0': True,
  'ownrent_fuzzy_0': True,
  'marryun_fuzzy_0': True,
  'marryyes_fuzzy_0': True,
  'mailord_fuzzy_0': True,
  'mailres_fuzzy_0': True,
  'mailflag_fuzzy_0': True,
  'travel_fuzzy_0': True,
  'pcown_fuzzy_0': True,
  'creditcd_fuzzy_1': True,
  'retcalls_fuzzy_0': True,
  'retaccpt_fuzzy_0': True,
  'newcelly_fuzzy_0': True,
  'newcelln_fuzzy_0': True,
  'refer_fuzzy_0': True,
  'incmiss_fuzzy_0': True,
  'income_fuzzy_2': True,
  'mcycle_fuzzy_0': True,
  'setprcm_fuzzy_1': True,
  'setprc_fuzzy_0': True,
  'retcall_fuzzy_0': True},
 'transaction9': {'revenue_fuzzy_1': True,
  'mou_fuzzy_0': True,
  'recchrge_fuzzy_1': True,
  'directas_fuzzy_0': True,
  'overage_fuzzy_0': True,
  'roam_fuzzy_0': True,
  'changem_fuzzy_1': True,
  'changer_fuzzy_1': True,
  'dropvce_fuzzy_0': True,
  'blckvce_fuzzy_0': True,
  'unansvce_fuzzy_0': True,
  'custcare_fuzzy_0': True,
  'threeway_fuzzy_0': True,
  'mourec_fuzzy_0': True,
  'outcalls_fuzzy_0': True,
  'incalls_fuzzy_0': True,
  'peakvce_fuzzy_0': True,
  'opeakvce_fuzzy_0': True,
  'dropblk_fuzzy_0': True,
  'callfwdv_fuzzy_0': True,
  'callwait_fuzzy_0': True,
  'months_fuzzy_2': True,
  'uniqsubs_fuzzy_0': True,
  'actvsubs_fuzzy_1': True,
  'phones_fuzzy_0': True,
  'models_fuzzy_0': True,
  'eqpdays_fuzzy_2': True,
  'age1_fuzzy_1': True,
  'age2_fuzzy_2': True,
  'children_fuzzy_0': True,
  'credita_fuzzy_2': True,
  'creditaa_fuzzy_0': True,
  'prizmrur_fuzzy_0': True,
  'prizmub_fuzzy_2': True,
  'prizmtwn_fuzzy_0': True,
  'refurb_fuzzy_0': True,
  'webcap_fuzzy_0': True,
  'truck_fuzzy_0': True,
  'rv_fuzzy_0': True,
  'occprof_fuzzy_2': True,
  'occcler_fuzzy_0': True,
  'occcrft_fuzzy_0': True,
  'occstud_fuzzy_0': True,
  'occhmkr_fuzzy_0': True,
  'occret_fuzzy_0': True,
  'occself_fuzzy_0': True,
  'ownrent_fuzzy_0': True,
  'marryun_fuzzy_0': True,
  'marryyes_fuzzy_2': True,
  'mailord_fuzzy_2': True,
  'mailres_fuzzy_2': True,
  'mailflag_fuzzy_0': True,
  'travel_fuzzy_2': True,
  'pcown_fuzzy_0': True,
  'creditcd_fuzzy_1': True,
  'retcalls_fuzzy_0': True,
  'retaccpt_fuzzy_0': True,
  'newcelly_fuzzy_2': True,
  'newcelln_fuzzy_0': True,
  'refer_fuzzy_0': True,
  'incmiss_fuzzy_0': True,
  'income_fuzzy_2': True,
  'mcycle_fuzzy_0': True,
  'setprcm_fuzzy_1': True,
  'setprc_fuzzy_0': True,
  'retcall_fuzzy_0': True},
 'transaction10': {'revenue_fuzzy_1': True,
  'mou_fuzzy_1': True,
  'recchrge_fuzzy_1': True,
  'directas_fuzzy_1': True,
  'overage_fuzzy_1': True,
  'roam_fuzzy_0': True,
  'changem_fuzzy_1': True,
  'changer_fuzzy_1': True,
  'dropvce_fuzzy_1': True,
  'blckvce_fuzzy_1': True,
  'unansvce_fuzzy_1': True,
  'custcare_fuzzy_1': True,
  'threeway_fuzzy_1': True,
  'mourec_fuzzy_1': True,
  'outcalls_fuzzy_1': True,
  'incalls_fuzzy_1': True,
  'peakvce_fuzzy_1': True,
  'opeakvce_fuzzy_1': True,
  'dropblk_fuzzy_1': True,
  'callfwdv_fuzzy_1': True,
  'callwait_fuzzy_1': True,
  'months_fuzzy_0': True,
  'uniqsubs_fuzzy_0': True,
  'actvsubs_fuzzy_1': True,
  'phones_fuzzy_0': True,
  'models_fuzzy_0': True,
  'eqpdays_fuzzy_1': True,
  'age1_fuzzy_0': True,
  'age2_fuzzy_0': True,
  'children_fuzzy_0': True,
  'credita_fuzzy_2': True,
  'creditaa_fuzzy_0': True,
  'prizmrur_fuzzy_0': True,
  'prizmub_fuzzy_0': True,
  'prizmtwn_fuzzy_0': True,
  'refurb_fuzzy_0': True,
  'webcap_fuzzy_1': True,
  'truck_fuzzy_0': True,
  'rv_fuzzy_0': True,
  'occprof_fuzzy_0': True,
  'occcler_fuzzy_0': True,
  'occcrft_fuzzy_0': True,
  'occstud_fuzzy_0': True,
  'occhmkr_fuzzy_0': True,
  'occret_fuzzy_0': True,
  'occself_fuzzy_0': True,
  'ownrent_fuzzy_2': True,
  'marryun_fuzzy_2': True,
  'marryyes_fuzzy_0': True,
  'mailord_fuzzy_0': True,
  'mailres_fuzzy_0': True,
  'mailflag_fuzzy_0': True,
  'travel_fuzzy_0': True,
  'pcown_fuzzy_0': True,
  'creditcd_fuzzy_0': True,
  'retcalls_fuzzy_0': True,
  'retaccpt_fuzzy_0': True,
  'newcelly_fuzzy_0': True,
  'newcelln_fuzzy_0': True,
  'refer_fuzzy_0': True,
  'incmiss_fuzzy_2': True,
  'income_fuzzy_0': True,
  'mcycle_fuzzy_0': True,
  'setprcm_fuzzy_1': True,
  'setprc_fuzzy_0': True,
  'retcall_fuzzy_0': True},
 'transaction11': {'revenue_fuzzy_1': True,
  'mou_fuzzy_0': True,
  'recchrge_fuzzy_1': True,
  'directas_fuzzy_0': True,
  'overage_fuzzy_0': True,
  'roam_fuzzy_1': True,
  'changem_fuzzy_1': True,
  'changer_fuzzy_1': True,
  'dropvce_fuzzy_0': True,
  'blckvce_fuzzy_0': True,
  'unansvce_fuzzy_0': True,
  'custcare_fuzzy_0': True,
  'threeway_fuzzy_0': True,
  'mourec_fuzzy_0': True,
  'outcalls_fuzzy_1': True,
  'incalls_fuzzy_0': True,
  'peakvce_fuzzy_0': True,
  'opeakvce_fuzzy_0': True,
  'dropblk_fuzzy_0': True,
  'callfwdv_fuzzy_0': True,
  'callwait_fuzzy_1': True,
  'months_fuzzy_1': True,
  'uniqsubs_fuzzy_0': True,
  'actvsubs_fuzzy_1': True,
  'phones_fuzzy_0': True,
  'models_fuzzy_0': True,
  'eqpdays_fuzzy_1': True,
  'age1_fuzzy_0': True,
  'age2_fuzzy_0': True,
  'children_fuzzy_0': True,
  'credita_fuzzy_0': True,
  'creditaa_fuzzy_0': True,
  'prizmrur_fuzzy_0': True,
  'prizmub_fuzzy_2': True,
  'prizmtwn_fuzzy_0': True,
  'refurb_fuzzy_0': True,
  'webcap_fuzzy_1': True,
  'truck_fuzzy_0': True,
  'rv_fuzzy_0': True,
  'occprof_fuzzy_0': True,
  'occcler_fuzzy_0': True,
  'occcrft_fuzzy_0': True,
  'occstud_fuzzy_0': True,
  'occhmkr_fuzzy_0': True,
  'occret_fuzzy_0': True,
  'occself_fuzzy_0': True,
  'ownrent_fuzzy_2': True,
  'marryun_fuzzy_2': True,
  'marryyes_fuzzy_0': True,
  'mailord_fuzzy_0': True,
  'mailres_fuzzy_0': True,
  'mailflag_fuzzy_0': True,
  'travel_fuzzy_0': True,
  'pcown_fuzzy_0': True,
  'creditcd_fuzzy_0': True,
  'retcalls_fuzzy_0': True,
  'retaccpt_fuzzy_0': True,
  'newcelly_fuzzy_0': True,
  'newcelln_fuzzy_0': True,
  'refer_fuzzy_0': True,
  'incmiss_fuzzy_2': True,
  'income_fuzzy_0': True,
  'mcycle_fuzzy_0': True,
  'setprcm_fuzzy_1': True,
  'setprc_fuzzy_0': True,
  'retcall_fuzzy_0': True},
 'transaction12': {'revenue_fuzzy_1': True,
  'mou_fuzzy_0': True,
  'recchrge_fuzzy_1': True,
  'directas_fuzzy_0': True,
  'overage_fuzzy_0': True,
  'roam_fuzzy_1': True,
  'changem_fuzzy_1': True,
  'changer_fuzzy_1': True,
  'dropvce_fuzzy_1': True,
  'blckvce_fuzzy_1': True,
  'unansvce_fuzzy_0': True,
  'custcare_fuzzy_0': True,

### High Utility fuzzy Churn Patterns

In [ ]:
import time

def extract_base_name(fuzzy_name):
    if fuzzy_name.startswith("Status_"):
        return "Status"
    elif fuzzy_name.startswith("Age Group_"):
        return "Age Group"
    elif fuzzy_name.startswith("Tariff Plan_"):
        return "Tariff Plan"
    elif "fuzzy" in fuzzy_name:
        return fuzzy_name.split("_", 1)[0]
    else:
        return fuzzy_name

def calculate_utility(itemset, transactions, profit_table):
    total_utility = 0
    for transaction in transactions.values():
        if set(itemset).issubset(set(transaction.keys())):
            for item, utility in transaction.items():
                if item in itemset:
                    base_name = extract_base_name(item)
                    total_utility += utility * profit_table.get(base_name, 0)
    return total_utility

def find_top_k_high_utility_itemsets(transactions, profit_table, k):
    itemsets = set()
    for transaction in transactions.values():
        itemsets.update(transaction.keys())

    high_utility_itemsets = {}
    for item in itemsets:
        utility = calculate_utility([item], transactions, profit_table)
        if utility > 0:
            high_utility_itemsets[(item,)] = utility

    P_itemsets = {}
    while True:
        temp_itemsets = {}
        for itemset, utility in high_utility_itemsets.items():
            for item in itemsets:
                if item not in itemset:
                    new_itemset = tuple(sorted(list(itemset) + [item]))
                    new_utility = calculate_utility(new_itemset, transactions, profit_table)
                    if new_utility > 0:
                        temp_itemsets[new_itemset] = new_utility
                        P_itemsets[new_itemset] = new_utility

        if not temp_itemsets:
            break

        sorted_itemsets = sorted(temp_itemsets.items(), key=lambda x: x[1], reverse=True)
        top_k_itemsets = sorted_itemsets[:k]
        high_utility_itemsets = {itemset: utility for itemset, utility in top_k_itemsets}

    return high_utility_itemsets, P_itemsets

def find_top_k_high_utility_itemsets(transactions, profit_table, k, desired_length):
    """
    Tìm ra K tập mục có độ hữu ích cao nhất với độ dài tối đa được chỉ định.
    """
    itemsets = set()
    for transaction in transactions.values():
        # Thêm từng mục trong giao dịch vào tập hợp itemsets
        itemsets.update(transaction.keys())

    # Lưu trữ các tập mục có độ hữu ích cao và tổng giá trị của chúng
    high_utility_itemsets = {}
    P_itemsets = {}

    for item in itemsets:
        utility = calculate_utility([item], transactions, profit_table)
        if utility > 0:
            high_utility_itemsets[(item,)] = utility

    while True:
        temp_itemsets = {}
        for itemset, utility in high_utility_itemsets.items():
            for item in itemsets:
                if item not in itemset:
                    # Tạo tập mục mới bằng cách kết hợp
                    new_itemset = tuple(sorted(list(itemset) + [item]))
                    new_utility = calculate_utility(new_itemset, transactions, profit_table)

                    # Kiểm tra điều kiện độ dài và độ hữu ích
                    if new_utility > 0 and len(new_itemset) <= desired_length:
                        temp_itemsets[new_itemset] = new_utility
                        P_itemsets[new_itemset] = new_utility

        if not temp_itemsets:
            break

        # Lấy top K tập mục có độ hữu ích cao nhất
        sorted_itemsets = sorted(temp_itemsets.items(), key=lambda x: x[1], reverse=True)
        top_k_itemsets = sorted_itemsets[:k]
        high_utility_itemsets = {itemset: utility for itemset, utility in top_k_itemsets}

    return high_utility_itemsets, P_itemsets

In [ ]:
result,P_itemsets= find_top_k_high_utility_itemsets(filtered_transactions, profit_table, 3,2)


sorted_data = sorted(P_itemsets.items(), key=lambda x: x[1], reverse=True)


top_10 = sorted_data[:10]
top_10 = {itemset: value for itemset, value in top_10}

print("Top 10 High Utility Itemsets:")
for itemset, utility in top_10.items():
    print(itemset, "-> Utility:", round(utility,0))

Top 10 High Utility Itemsets:
('changem_fuzzy_1', 'eqpdays_fuzzy_1') -> Utility: 7573.0
('eqpdays_fuzzy_1', 'months_fuzzy_1') -> Utility: 6384.0
('creditaa_fuzzy_0', 'eqpdays_fuzzy_1') -> Utility: 5974.0
('eqpdays_fuzzy_1', 'mou_fuzzy_1') -> Utility: 5949.0
('actvsubs_fuzzy_1', 'eqpdays_fuzzy_1') -> Utility: 5938.0
('eqpdays_fuzzy_1', 'recchrge_fuzzy_1') -> Utility: 5858.0
('changer_fuzzy_1', 'eqpdays_fuzzy_1') -> Utility: 5787.0
('changem_fuzzy_1', 'months_fuzzy_1') -> Utility: 5374.0
('credita_fuzzy_0', 'eqpdays_fuzzy_1') -> Utility: 5331.0
('eqpdays_fuzzy_1', 'webcap_fuzzy_1') -> Utility: 5324.0

In [ ]:

fuzzy_df = pd.DataFrame()
for feature in Xtofuzzy_Tri.columns:
    min_val = Xtofuzzy_Tri[feature].min()
    median_val = Xtofuzzy_Tri[feature].quantile(0.5)
    max_val = Xtofuzzy_Tri[feature].max()

    fuzzy_df[f'{feature}_fuzzy'] = Xtofuzzy_Tri[feature].apply(lambda x: fuzzy_classification(x, min_val, median_val, max_val))


df_fuzzy = fuzzy_df

fuzzy_columns = [col for col in df_fuzzy.columns]

df_fuzzy = pd.get_dummies(df_fuzzy, columns=fuzzy_columns)
df_fuzzy =df_fuzzy.astype(int)
df_fuzzy

,revenue_fuzzy_0,revenue_fuzzy_1,revenue_fuzzy_2,mou_fuzzy_0,mou_fuzzy_1,mou_fuzzy_2,recchrge_fuzzy_0,recchrge_fuzzy_1,recchrge_fuzzy_2,directas_fuzzy_0,...,income_fuzzy_2,mcycle_fuzzy_0,mcycle_fuzzy_2,setprcm_fuzzy_0,setprcm_fuzzy_1,setprc_fuzzy_0,setprc_fuzzy_1,setprc_fuzzy_2,retcall_fuzzy_0,retcall_fuzzy_2
52253,0,1,0,1,0,0,0,1,0,1,...,0,1,0,0,1,1,0,0,1,0
63241,0,1,0,0,1,0,0,1,0,0,...,0,1,0,0,1,1,0,0,1,0
67661,0,1,0,1,0,0,0,1,0,0,...,1,1,0,0,1,1,0,0,1,0
53577,0,1,0,0,1,0,0,1,0,0,...,0,1,0,1,0,0,1,0,1,0
52347,0,1,0,1,0,0,0,1,0,0,...,0,0,1,1,0,0,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61120,0,1,0,0,1,0,0,1,0,0,...,1,1,0,1,0,0,1,0,1,0
66341,0,1,0,0,1,0,0,1,0,1,...,0,1,0,1,0,0,1,0,1,0
68840,1,0,0,1,0,0,1,0,0,1,...,0,1,0,0,1,1,0,0,1,0
61658,0,1,0,0,1,0,0,1,0,0,...,1,1,0,1,0,0,1,0,1,0
56165,0,1,0,0,1,0,0,1,0,1,...,0,1,0,1,0,0,1,0,1,0

In [ ]:
Xy_merge = pd.merge(X_temp, df_fuzzy, left_index=True, right_index=True, how='left')
Xy_merge['fuzzyp1'] = Xy_merge['changem_fuzzy_1'] * Xy_merge['eqpdays_fuzzy_1']
Xy_merge['fuzzyp2'] = Xy_merge['eqpdays_fuzzy_1'] * Xy_merge['months_fuzzy_1']
Xy_merge['fuzzyp3'] = Xy_merge['creditaa_fuzzy_0'] * Xy_merge['eqpdays_fuzzy_1']
Xy_merge['fuzzyp4'] = Xy_merge['eqpdays_fuzzy_1'] * Xy_merge['mou_fuzzy_1']
Xy_merge['fuzzyp5'] = Xy_merge['actvsubs_fuzzy_1'] * Xy_merge['eqpdays_fuzzy_1']
Xy_merge['fuzzyp6'] = Xy_merge['eqpdays_fuzzy_1'] * Xy_merge['recchrge_fuzzy_1']
Xy_merge['fuzzyp7'] = Xy_merge['changer_fuzzy_1'] * Xy_merge['eqpdays_fuzzy_1']
Xy_merge['fuzzyp8'] = Xy_merge['changem_fuzzy_1'] * Xy_merge['months_fuzzy_1']
Xy_merge['fuzzyp9'] = Xy_merge['eqpdays_fuzzy_1'] * Xy_merge['webcap_fuzzy_1']
Xy_merge['fuzzyp10'] = Xy_merge['credita_fuzzy_0'] * Xy_merge['eqpdays_fuzzy_1']

print(Xy_merge.columns.tolist())

['revenue', 'mou', 'recchrge', 'directas', 'overage', 'roam', 'changem', 'changer', 'dropvce', 'blckvce', 'unansvce', 'custcare', 'threeway', 'mourec', 'outcalls', 'incalls', 'peakvce', 'opeakvce', 'dropblk', 'callfwdv', 'callwait', 'months', 'uniqsubs', 'actvsubs', 'phones', 'models', 'eqpdays', 'age1', 'age2', 'children', 'credita', 'creditaa', 'prizmrur', 'prizmub', 'prizmtwn', 'refurb', 'webcap', 'truck', 'rv', 'occprof', 'occcler', 'occcrft', 'occstud', 'occhmkr', 'occret', 'occself', 'ownrent', 'marryun', 'marryyes', 'mailord', 'mailres', 'mailflag', 'travel', 'pcown', 'creditcd', 'retcalls', 'retaccpt', 'newcelly', 'newcelln', 'refer', 'incmiss', 'income', 'mcycle', 'setprcm', 'setprc', 'retcall', 'churn', 'revenue_fuzzy_0', 'revenue_fuzzy_1', 'revenue_fuzzy_2', 'mou_fuzzy_0', 'mou_fuzzy_1', 'mou_fuzzy_2', 'recchrge_fuzzy_0', 'recchrge_fuzzy_1', 'recchrge_fuzzy_2', 'directas_fuzzy_0', 'directas_fuzzy_1', 'directas_fuzzy_2', 'overage_fuzzy_0', 'overage_fuzzy_1', 'overage_fuzzy_2', 'roam_fuzzy_0', 'roam_fuzzy_1', 'roam_fuzzy_2', 'changem_fuzzy_0', 'changem_fuzzy_1', 'changem_fuzzy_2', 'changer_fuzzy_0', 'changer_fuzzy_1', 'changer_fuzzy_2', 'dropvce_fuzzy_0', 'dropvce_fuzzy_1', 'dropvce_fuzzy_2', 'blckvce_fuzzy_0', 'blckvce_fuzzy_1', 'blckvce_fuzzy_2', 'unansvce_fuzzy_0', 'unansvce_fuzzy_1', 'unansvce_fuzzy_2', 'custcare_fuzzy_0', 'custcare_fuzzy_1', 'custcare_fuzzy_2', 'threeway_fuzzy_0', 'threeway_fuzzy_1', 'threeway_fuzzy_2', 'mourec_fuzzy_0', 'mourec_fuzzy_1', 'mourec_fuzzy_2', 'outcalls_fuzzy_0', 'outcalls_fuzzy_1', 'outcalls_fuzzy_2', 'incalls_fuzzy_0', 'incalls_fuzzy_1', 'incalls_fuzzy_2', 'peakvce_fuzzy_0', 'peakvce_fuzzy_1', 'peakvce_fuzzy_2', 'opeakvce_fuzzy_0', 'opeakvce_fuzzy_1', 'opeakvce_fuzzy_2', 'dropblk_fuzzy_0', 'dropblk_fuzzy_1', 'dropblk_fuzzy_2', 'callfwdv_fuzzy_0', 'callfwdv_fuzzy_1', 'callfwdv_fuzzy_2', 'callwait_fuzzy_0', 'callwait_fuzzy_1', 'callwait_fuzzy_2', 'months_fuzzy_0', 'months_fuzzy_1', 'months_fuzzy_2', 'uniqsubs_fuzzy_0', 'uniqsubs_fuzzy_1', 'uniqsubs_fuzzy_2', 'actvsubs_fuzzy_0', 'actvsubs_fuzzy_1', 'actvsubs_fuzzy_2', 'phones_fuzzy_0', 'phones_fuzzy_1', 'phones_fuzzy_2', 'models_fuzzy_0', 'models_fuzzy_1', 'models_fuzzy_2', 'eqpdays_fuzzy_0', 'eqpdays_fuzzy_1', 'eqpdays_fuzzy_2', 'age1_fuzzy_0', 'age1_fuzzy_1', 'age1_fuzzy_2', 'age2_fuzzy_0', 'age2_fuzzy_1', 'age2_fuzzy_2', 'children_fuzzy_0', 'children_fuzzy_2', 'credita_fuzzy_0', 'credita_fuzzy_2', 'creditaa_fuzzy_0', 'creditaa_fuzzy_2', 'prizmrur_fuzzy_0', 'prizmrur_fuzzy_2', 'prizmub_fuzzy_0', 'prizmub_fuzzy_2', 'prizmtwn_fuzzy_0', 'prizmtwn_fuzzy_2', 'refurb_fuzzy_0', 'refurb_fuzzy_2', 'webcap_fuzzy_0', 'webcap_fuzzy_1', 'truck_fuzzy_0', 'truck_fuzzy_2', 'rv_fuzzy_0', 'rv_fuzzy_2', 'occprof_fuzzy_0', 'occprof_fuzzy_2', 'occcler_fuzzy_0', 'occcler_fuzzy_2', 'occcrft_fuzzy_0', 'occcrft_fuzzy_2', 'occstud_fuzzy_0', 'occstud_fuzzy_2', 'occhmkr_fuzzy_0', 'occhmkr_fuzzy_2', 'occret_fuzzy_0', 'occret_fuzzy_2', 'occself_fuzzy_0', 'occself_fuzzy_2', 'ownrent_fuzzy_0', 'ownrent_fuzzy_2', 'marryun_fuzzy_0', 'marryun_fuzzy_2', 'marryyes_fuzzy_0', 'marryyes_fuzzy_2', 'mailord_fuzzy_0', 'mailord_fuzzy_2', 'mailres_fuzzy_0', 'mailres_fuzzy_2', 'mailflag_fuzzy_0', 'mailflag_fuzzy_2', 'travel_fuzzy_0', 'travel_fuzzy_2', 'pcown_fuzzy_0', 'pcown_fuzzy_2', 'creditcd_fuzzy_0', 'creditcd_fuzzy_1', 'retcalls_fuzzy_0', 'retcalls_fuzzy_1', 'retcalls_fuzzy_2', 'retaccpt_fuzzy_0', 'retaccpt_fuzzy_1', 'retaccpt_fuzzy_2', 'newcelly_fuzzy_0', 'newcelly_fuzzy_2', 'newcelln_fuzzy_0', 'newcelln_fuzzy_2', 'refer_fuzzy_0', 'refer_fuzzy_1', 'refer_fuzzy_2', 'incmiss_fuzzy_0', 'incmiss_fuzzy_2', 'income_fuzzy_0', 'income_fuzzy_1', 'income_fuzzy_2', 'mcycle_fuzzy_0', 'mcycle_fuzzy_2', 'setprcm_fuzzy_0', 'setprcm_fuzzy_1', 'setprc_fuzzy_0', 'setprc_fuzzy_1', 'setprc_fuzzy_2', 'retcall_fuzzy_0', 'retcall_fuzzy_2', 'fuzzyp1', 'fuzzyp2', 'fuzzyp3', 'fuzzyp4', 'fuzzyp5', 'fuzzyp6', 'fuzzyp7', 'fuzzyp8', 'fuzzyp9', 'fuzzyp10']

In [ ]:
Xy_merge = Xy_merge.fillna(0)

In [ ]:
columns_to_keep = [
    'revenue', 'mou', 'recchrge', 'directas', 'overage', 'roam', 'changem', 'changer',
    'dropvce', 'blckvce', 'unansvce', 'custcare', 'threeway', 'mourec', 'outcalls', 'incalls',
    'peakvce', 'opeakvce', 'dropblk', 'callfwdv', 'callwait', 'months', 'uniqsubs', 'actvsubs',
    'phones', 'models', 'eqpdays', 'age1', 'age2', 'children', 'credita', 'creditaa', 'prizmrur',
    'prizmub', 'prizmtwn', 'refurb', 'webcap', 'truck', 'rv', 'occprof', 'occcler', 'occcrft',
    'occstud', 'occhmkr', 'occret', 'occself', 'ownrent', 'marryun', 'marryyes', 'mailord',
    'mailres', 'mailflag', 'travel', 'pcown', 'creditcd', 'retcalls', 'retaccpt', 'newcelly',
    'newcelln', 'refer', 'incmiss', 'income', 'mcycle', 'setprcm', 'setprc', 'retcall',
    'fuzzyp1', 'fuzzyp2', 'fuzzyp3', 'fuzzyp4', 'fuzzyp5', 'fuzzyp6', 'fuzzyp7', 'fuzzyp8',
    'fuzzyp9', 'fuzzyp10'
]
X_train_2 = Xy_merge[columns_to_keep]
y_train_2 = Xy_merge['churn']

# HAFCP Model For Test dataset

## Highly Associated Fuzzy Churn Patterns in Binary Classification

### Fuzzy Triangle & Gaussion

In [23]:
X_temp_test = pd.concat([X_test,y_test],axis=1)

# Lấy ra các row nhãn là churn
X_churn_label = X_temp_test[X_temp_test['churn'] == 1]

X_churn_label

,revenue,mou,recchrge,directas,overage,roam,changem,changer,dropvce,blckvce,...,newcelly,newcelln,refer,incmiss,income,mcycle,setprcm,setprc,retcall,churn
54569,34.145000,318.75,24.990000,0.000,0.00,9.1550,220.25,22.844999,0.333333,1.333333,...,0,1,0,0,6,1,1,0.00000,0,1
52439,79.964996,354.50,69.989998,0.000,54.00,0.0000,-107.50,-16.725000,19.666666,1.666667,...,0,1,0,0,7,0,0,29.98999,0,1
63639,30.260000,88.75,39.990002,0.000,0.00,0.0000,-2.75,-0.270000,0.666667,0.000000,...,0,0,0,0,3,0,1,0.00000,0,1
57383,155.212494,1342.75,47.572498,2.475,298.00,4.5325,-222.75,-37.222500,8.666667,14.000000,...,0,0,0,0,5,0,0,79.98999,0,1
70085,189.570007,1658.00,78.029999,0.000,325.75,8.6750,160.00,-9.190000,13.333333,12.333333,...,1,0,0,0,4,0,1,0.00000,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55990,31.795000,239.75,29.990000,0.000,3.25,0.4800,-83.75,-1.805000,0.333333,6.666667,...,0,0,0,0,4,0,1,0.00000,0,1
53067,32.490002,136.75,32.490002,0.000,0.00,0.0000,-1.75,0.000000,0.333333,1.666667,...,0,1,0,0,8,0,1,0.00000,0,1
53682,54.482498,411.75,59.990002,0.000,0.00,1.2175,-120.75,-1.242500,44.333332,10.666667,...,1,0,0,0,4,0,0,149.98999,0,1
51952,29.990000,253.25,39.990002,0.000,0.00,0.0000,124.75,0.000000,2.333333,1.000000,...,1,0,0,0,8,0,0,29.98999,0,1
58158,71.739998,341.50,37.750000,0.000,73.25,0.9400,-163.50,6.950000,14.333333,0.000000,...,0,1,0,0,1,0,0,79.98999,0,1

In [24]:
def print_column_names(X_churn_label):
    print("Các cột trong DataFrame là:")
    print(list(X_churn_label.columns))
print_column_names(X_churn_label)

Các cột trong DataFrame là:
['revenue', 'mou', 'recchrge', 'directas', 'overage', 'roam', 'changem', 'changer', 'dropvce', 'blckvce', 'unansvce', 'custcare', 'threeway', 'mourec', 'outcalls', 'incalls', 'peakvce', 'opeakvce', 'dropblk', 'callfwdv', 'callwait', 'months', 'uniqsubs', 'actvsubs', 'phones', 'models', 'eqpdays', 'age1', 'age2', 'children', 'credita', 'creditaa', 'prizmrur', 'prizmub', 'prizmtwn', 'refurb', 'webcap', 'truck', 'rv', 'occprof', 'occcler', 'occcrft', 'occstud', 'occhmkr', 'occret', 'occself', 'ownrent', 'marryun', 'marryyes', 'mailord', 'mailres', 'mailflag', 'travel', 'pcown', 'creditcd', 'retcalls', 'retaccpt', 'newcelly', 'newcelln', 'refer', 'incmiss', 'income', 'mcycle', 'setprcm', 'setprc', 'retcall', 'churn']

In [25]:
X_churn_label.shape

(3991, 67)

In [26]:
Xtofuzzy_Tri  = X_churn_label[['revenue', 'mou', 'recchrge', 'directas', 'overage', 'roam', 'changem', 'changer', 'dropvce', 'blckvce', 'unansvce', 'custcare', 'threeway', 'mourec', 'outcalls', 'incalls', 'peakvce', 'opeakvce', 'dropblk', 'callfwdv', 'callwait', 'months', 'uniqsubs', 'actvsubs', 'phones', 'models', 'eqpdays', 'age1', 'age2', 'children', 'credita', 'creditaa', 'prizmrur', 'prizmub', 'prizmtwn', 'refurb', 'webcap', 'truck', 'rv', 'occprof', 'occcler', 'occcrft', 'occstud', 'occhmkr', 'occret', 'occself', 'ownrent', 'marryun', 'marryyes', 'mailord', 'mailres', 'mailflag', 'travel', 'pcown', 'creditcd', 'retcalls', 'retaccpt', 'newcelly', 'newcelln', 'refer', 'incmiss', 'income', 'mcycle', 'setprcm', 'setprc', 'retcall']]

In [27]:
import pandas as pd

# Membership function
def triangular_mf(x, a, b, c):
    if x <= a:
        return 0
    elif a < x <= b:
        return (x - a) / (b - a)
    elif b < x <= c:
        return (c - x) / (c - b)
    else:
        return 0

# Maximal cardinality
def fuzzy_classification(x, min_val, median_val, max_val):
    low_membership = triangular_mf(x, min_val, min_val, median_val)
    medium_membership = triangular_mf(x, min_val, median_val, max_val)
    high_membership = triangular_mf(x, median_val, max_val, max_val)

    max_membership = max(low_membership, medium_membership, high_membership)

    if max_membership == low_membership:
        return 0
    elif max_membership == medium_membership:
        return 1
    else:
        return 2


fuzzy_df = pd.DataFrame()
# For each feature
for feature in Xtofuzzy_Tri.columns:
    min_val = Xtofuzzy_Tri[feature].min()
    median_val = Xtofuzzy_Tri[feature].quantile(0.5)
    max_val = Xtofuzzy_Tri[feature].max()

    fuzzy_df[f'{feature}_fuzzy'] = Xtofuzzy_Tri[feature].apply(lambda x: fuzzy_classification(x, min_val, median_val, max_val))

fuzzy_df

# Define a dict
boundaries = {}

for feature in Xtofuzzy_Tri.columns:
    min_val = Xtofuzzy_Tri[feature].min()
    median_val = Xtofuzzy_Tri[feature].quantile(0.5)
    max_val = Xtofuzzy_Tri[feature].max()

    # Save
    boundaries[feature] = (min_val, median_val, max_val)

# print out
for feature, bounds in boundaries.items():
    print(f"Feature: {feature}")
    print(f"Low boundary: {bounds[0]}, Medium boundary: {bounds[1]}, High boundary: {bounds[2]}")
    print("------")

fuzzy_df

Feature: revenue
Low boundary: 2.537499905, Medium boundary: 47.88000107, High boundary: 595.4324951
------
Feature: mou
Low boundary: 0.0, Medium boundary: 328.25, High boundary: 4258.25
------
Feature: recchrge
Low boundary: 0.0, Medium boundary: 44.98749924, High boundary: 243.7400055
------
Feature: directas
Low boundary: 0.0, Medium boundary: 0.247500002, High boundary: 31.18499947
------
Feature: overage
Low boundary: 0.0, Medium boundary: 3.0, High boundary: 1149.25
------
Feature: roam
Low boundary: 0.0, Medium boundary: 0.0, High boundary: 151.3200073
------
Feature: changem
Low boundary: -1941.25, Medium boundary: -9.5, High boundary: 3046.75
------
Feature: changer
Low boundary: -439.5025024, Medium boundary: -0.292499989, High boundary: 619.6799927
------
Feature: dropvce
Low boundary: 0.0, Medium boundary: 3.0, High boundary: 145.3333282
------
Feature: blckvce
Low boundary: 0.0, Medium boundary: 1.0, High boundary: 286.3333435
------
Feature: unansvce
Low boundary: 0.0, Medium boundary: 14.66666698, High boundary: 848.666687
------
Feature: custcare
Low boundary: 0.0, Medium boundary: 0.0, High boundary: 75.0
------
Feature: threeway
Low boundary: 0.0, Medium boundary: 0.0, High boundary: 29.0
------
Feature: mourec
Low boundary: 0.0, Medium boundary: 44.43333435, High boundary: 2619.280029
------
Feature: outcalls
Low boundary: 0.0, Medium boundary: 11.66666698, High boundary: 455.0
------
Feature: incalls
Low boundary: 0.0, Medium boundary: 1.333333373, High boundary: 298.3333435
------
Feature: peakvce
Low boundary: 0.0, Medium boundary: 58.0, High boundary: 1005.333313
------
Feature: opeakvce
Low boundary: 0.0, Medium boundary: 30.66666603, High boundary: 1313.666626
------
Feature: dropblk
Low boundary: 0.0, Medium boundary: 5.333333492, High boundary: 288.0
------
Feature: callfwdv
Low boundary: 0.0, Medium boundary: 0.0, High boundary: 1.333333373
------
Feature: callwait
Low boundary: 0.0, Medium boundary: 0.0, High boundary: 126.3333359
------
Feature: months
Low boundary: 6, Medium boundary: 16.0, High boundary: 58
------
Feature: uniqsubs
Low boundary: 1, Medium boundary: 1.0, High boundary: 18
------
Feature: actvsubs
Low boundary: 1, Medium boundary: 1.0, High boundary: 8
------
Feature: phones
Low boundary: 1.0, Medium boundary: 1.0, High boundary: 19.0
------
Feature: models
Low boundary: 1.0, Medium boundary: 1.0, High boundary: 10.0
------
Feature: eqpdays
Low boundary: -3.0, Medium boundary: 367.0, High boundary: 1669.0
------
Feature: age1
Low boundary: 0.0, Medium boundary: 34.0, High boundary: 94.0
------
Feature: age2
Low boundary: 0.0, Medium boundary: 0.0, High boundary: 90.0
------
Feature: children
Low boundary: 0, Medium boundary: 0.0, High boundary: 1
------
Feature: credita
Low boundary: 0, Medium boundary: 0.0, High boundary: 1
------
Feature: creditaa
Low boundary: 0, Medium boundary: 0.0, High boundary: 1
------
Feature: prizmrur
Low boundary: 0, Medium boundary: 0.0, High boundary: 1
------
Feature: prizmub
Low boundary: 0, Medium boundary: 0.0, High boundary: 1
------
Feature: prizmtwn
Low boundary: 0, Medium boundary: 0.0, High boundary: 1
------
Feature: refurb
Low boundary: 0, Medium boundary: 0.0, High boundary: 1
------
Feature: webcap
Low boundary: 0, Medium boundary: 1.0, High boundary: 1
------
Feature: truck
Low boundary: 0, Medium boundary: 0.0, High boundary: 1
------
Feature: rv
Low boundary: 0, Medium boundary: 0.0, High boundary: 1
------
Feature: occprof
Low boundary: 0, Medium boundary: 0.0, High boundary: 1
------
Feature: occcler
Low boundary: 0, Medium boundary: 0.0, High boundary: 1
------
Feature: occcrft
Low boundary: 0, Medium boundary: 0.0, High boundary: 1
------
Feature: occstud
Low boundary: 0, Medium boundary: 0.0, High boundary: 1
------
Feature: occhmkr
Low boundary: 0, Medium boundary: 0.0, High boundary: 1
------
Feature: occret
Low boundary: 0, Medium boundary: 0.0, High boundary: 1
------
Feature: occself
Low boundary: 0, Medium boundary: 0.0, High boundary: 1
------
Feature: ownrent
Low boundary: 0, Medium boundary: 0.0, High boundary: 1
------
Feature: marryun
Low boundary: 0, Medium boundary: 0.0, High boundary: 1
------
Feature: marryyes
Low boundary: 0, Medium boundary: 0.0, High boundary: 1
------
Feature: mailord
Low boundary: 0, Medium boundary: 0.0, High boundary: 1
------
Feature: mailres
Low boundary: 0, Medium boundary: 0.0, High boundary: 1
------
Feature: mailflag
Low boundary: 0, Medium boundary: 0.0, High boundary: 1
------
Feature: travel
Low boundary: 0, Medium boundary: 0.0, High boundary: 1
------
Feature: pcown
Low boundary: 0, Medium boundary: 0.0, High boundary: 1
------
Feature: creditcd
Low boundary: 0, Medium boundary: 1.0, High boundary: 1
------
Feature: retcalls
Low boundary: 0, Medium boundary: 0.0, High boundary: 4
------
Feature: retaccpt
Low boundary: 0, Medium boundary: 0.0, High boundary: 2
------
Feature: newcelly
Low boundary: 0, Medium boundary: 0.0, High boundary: 1
------
Feature: newcelln
Low boundary: 0, Medium boundary: 0.0, High boundary: 1
------
Feature: refer
Low boundary: 0, Medium boundary: 0.0, High boundary: 5
------
Feature: incmiss
Low boundary: 0, Medium boundary: 0.0, High boundary: 1
------
Feature: income
Low boundary: 0, Medium boundary: 5.0, High boundary: 9
------
Feature: mcycle
Low boundary: 0, Medium boundary: 0.0, High boundary: 1
------
Feature: setprcm
Low boundary: 0, Medium boundary: 1.0, High boundary: 1
------
Feature: setprc
Low boundary: 0.0, Medium boundary: 0.0, High boundary: 399.9899902
------
Feature: retcall
Low boundary: 0, Medium boundary: 0.0, High boundary: 1
------

,revenue_fuzzy,mou_fuzzy,recchrge_fuzzy,directas_fuzzy,overage_fuzzy,roam_fuzzy,changem_fuzzy,changer_fuzzy,dropvce_fuzzy,blckvce_fuzzy,...,retaccpt_fuzzy,newcelly_fuzzy,newcelln_fuzzy,refer_fuzzy,incmiss_fuzzy,income_fuzzy,mcycle_fuzzy,setprcm_fuzzy,setprc_fuzzy,retcall_fuzzy
54569,1,1,1,0,0,1,1,1,0,1,...,0,0,2,0,0,1,2,1,0,0
52439,1,1,1,0,1,0,1,1,1,1,...,0,0,2,0,0,1,0,0,1,0
63639,1,0,1,0,0,0,1,1,0,0,...,0,0,0,0,0,1,0,1,0,0
57383,1,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,1,0,0,1,0
70085,1,1,1,0,1,1,1,1,1,1,...,0,2,0,0,0,1,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55990,1,1,1,0,1,1,1,1,0,1,...,0,0,0,0,0,1,0,1,0,0
53067,1,0,1,0,0,0,1,1,0,1,...,0,0,2,0,0,2,0,1,0,0
53682,1,1,1,0,0,1,1,1,1,1,...,0,2,0,0,0,1,0,0,1,0
51952,1,1,1,0,0,0,1,1,1,1,...,0,2,0,0,0,2,0,0,1,0
58158,1,1,1,0,1,1,1,1,1,0,...,0,0,2,0,0,0,0,0,1,0

In [28]:

df_encoded = fuzzy_df
fuzzy_columns = [col for col in df_encoded.columns]

# one-hot encoding
df_encoded = pd.get_dummies(df_encoded, columns=fuzzy_columns)

for col in fuzzy_columns:
    mappings = {
        f"{col}_{i}": f"{col}_{i}" for i in range(3)
    }
    df_encoded.rename(columns=mappings, inplace=True)
df_encoded.columns

Index(['revenue_fuzzy_0', 'revenue_fuzzy_1', 'revenue_fuzzy_2', 'mou_fuzzy_0',
       'mou_fuzzy_1', 'mou_fuzzy_2', 'recchrge_fuzzy_0', 'recchrge_fuzzy_1',
       'recchrge_fuzzy_2', 'directas_fuzzy_0',
       ...
       'income_fuzzy_2', 'mcycle_fuzzy_0', 'mcycle_fuzzy_2', 'setprcm_fuzzy_0',
       'setprcm_fuzzy_1', 'setprc_fuzzy_0', 'setprc_fuzzy_1', 'setprc_fuzzy_2',
       'retcall_fuzzy_0', 'retcall_fuzzy_2'],
      dtype='object', length=166)

In [29]:
dataset = {}

transaction_id = 1
for _, row in df_encoded.iterrows():
    transaction = {}
    for column, value in row.items():
        transaction[column] = value
    transaction_key = f'transaction{transaction_id}'
    dataset[transaction_key] = transaction
    transaction_id += 1

In [30]:
transactions = dataset

filtered_transactions = {transaction: {key: value for key, value in items.items() if value != 0}
                        for transaction, items in transactions.items()}

filtered_transactions

{'transaction1': {'revenue_fuzzy_1': True,
  'mou_fuzzy_1': True,
  'recchrge_fuzzy_1': True,
  'directas_fuzzy_0': True,
  'overage_fuzzy_0': True,
  'roam_fuzzy_1': True,
  'changem_fuzzy_1': True,
  'changer_fuzzy_1': True,
  'dropvce_fuzzy_0': True,
  'blckvce_fuzzy_1': True,
  'unansvce_fuzzy_1': True,
  'custcare_fuzzy_0': True,
  'threeway_fuzzy_1': True,
  'mourec_fuzzy_0': True,
  'outcalls_fuzzy_0': True,
  'incalls_fuzzy_0': True,
  'peakvce_fuzzy_0': True,
  'opeakvce_fuzzy_1': True,
  'dropblk_fuzzy_0': True,
  'callfwdv_fuzzy_0': True,
  'callwait_fuzzy_0': True,
  'months_fuzzy_1': True,
  'uniqsubs_fuzzy_1': True,
  'actvsubs_fuzzy_0': True,
  'phones_fuzzy_0': True,
  'models_fuzzy_0': True,
  'eqpdays_fuzzy_1': True,
  'age1_fuzzy_1': True,
  'age2_fuzzy_1': True,
  'children_fuzzy_2': True,
  'credita_fuzzy_0': True,
  'creditaa_fuzzy_0': True,
  'prizmrur_fuzzy_0': True,
  'prizmub_fuzzy_0': True,
  'prizmtwn_fuzzy_2': True,
  'refurb_fuzzy_0': True,
  'webcap_fuzzy_1': True,
  'truck_fuzzy_0': True,
  'rv_fuzzy_0': True,
  'occprof_fuzzy_0': True,
  'occcler_fuzzy_0': True,
  'occcrft_fuzzy_0': True,
  'occstud_fuzzy_0': True,
  'occhmkr_fuzzy_0': True,
  'occret_fuzzy_0': True,
  'occself_fuzzy_0': True,
  'ownrent_fuzzy_0': True,
  'marryun_fuzzy_0': True,
  'marryyes_fuzzy_0': True,
  'mailord_fuzzy_2': True,
  'mailres_fuzzy_2': True,
  'mailflag_fuzzy_0': True,
  'travel_fuzzy_0': True,
  'pcown_fuzzy_0': True,
  'creditcd_fuzzy_1': True,
  'retcalls_fuzzy_0': True,
  'retaccpt_fuzzy_0': True,
  'newcelly_fuzzy_0': True,
  'newcelln_fuzzy_2': True,
  'refer_fuzzy_0': True,
  'incmiss_fuzzy_0': True,
  'income_fuzzy_1': True,
  'mcycle_fuzzy_2': True,
  'setprcm_fuzzy_1': True,
  'setprc_fuzzy_0': True,
  'retcall_fuzzy_0': True},
 'transaction2': {'revenue_fuzzy_1': True,
  'mou_fuzzy_1': True,
  'recchrge_fuzzy_1': True,
  'directas_fuzzy_0': True,
  'overage_fuzzy_1': True,
  'roam_fuzzy_0': True,
  'changem_fuzzy_1': True,
  'changer_fuzzy_1': True,
  'dropvce_fuzzy_1': True,
  'blckvce_fuzzy_1': True,
  'unansvce_fuzzy_1': True,
  'custcare_fuzzy_0': True,
  'threeway_fuzzy_0': True,
  'mourec_fuzzy_1': True,
  'outcalls_fuzzy_1': True,
  'incalls_fuzzy_1': True,
  'peakvce_fuzzy_1': True,
  'opeakvce_fuzzy_1': True,
  'dropblk_fuzzy_1': True,
  'callfwdv_fuzzy_0': True,
  'callwait_fuzzy_0': True,
  'months_fuzzy_1': True,
  'uniqsubs_fuzzy_1': True,
  'actvsubs_fuzzy_1': True,
  'phones_fuzzy_1': True,
  'models_fuzzy_1': True,
  'eqpdays_fuzzy_1': True,
  'age1_fuzzy_1': True,
  'age2_fuzzy_0': True,
  'children_fuzzy_2': True,
  'credita_fuzzy_0': True,
  'creditaa_fuzzy_0': True,
  'prizmrur_fuzzy_0': True,
  'prizmub_fuzzy_2': True,
  'prizmtwn_fuzzy_0': True,
  'refurb_fuzzy_0': True,
  'webcap_fuzzy_1': True,
  'truck_fuzzy_0': True,
  'rv_fuzzy_0': True,
  'occprof_fuzzy_0': True,
  'occcler_fuzzy_0': True,
  'occcrft_fuzzy_0': True,
  'occstud_fuzzy_0': True,
  'occhmkr_fuzzy_0': True,
  'occret_fuzzy_0': True,
  'occself_fuzzy_0': True,
  'ownrent_fuzzy_0': True,
  'marryun_fuzzy_0': True,
  'marryyes_fuzzy_2': True,
  'mailord_fuzzy_2': True,
  'mailres_fuzzy_2': True,
  'mailflag_fuzzy_0': True,
  'travel_fuzzy_0': True,
  'pcown_fuzzy_0': True,
  'creditcd_fuzzy_1': True,
  'retcalls_fuzzy_0': True,
  'retaccpt_fuzzy_0': True,
  'newcelly_fuzzy_0': True,
  'newcelln_fuzzy_2': True,
  'refer_fuzzy_0': True,
  'incmiss_fuzzy_0': True,
  'income_fuzzy_1': True,
  'mcycle_fuzzy_0': True,
  'setprcm_fuzzy_0': True,
  'setprc_fuzzy_1': True,
  'retcall_fuzzy_0': True},
 'transaction3': {'revenue_fuzzy_1': True,
  'mou_fuzzy_0': True,
  'recchrge_fuzzy_1': True,
  'directas_fuzzy_0': True,
  'overage_fuzzy_0': True,
  'roam_fuzzy_0': True,
  'changem_fuzzy_1': True,
  'changer_fuzzy_1': True,
  'dropvce_fuzzy_0': True,
  'blckvce_fuzzy_0': True,
  'unansvce_fuzzy_0': True,
  'custcare_fuzzy_0': True,
  'threeway_fuzzy_0': True,
  'mourec_fuzzy_1': True,
  'outcalls_fuzzy_0': True,
  'incalls_fuzzy_0': True,
  'peakvce_fuzzy_0': True,
  'opeakvce_fuzzy_0': True,
  'dropblk_fuzzy_0': True,
  'callfwdv_fuzzy_0': True,
  'callwait_fuzzy_0': True,
  'months_fuzzy_0': True,
  'uniqsubs_fuzzy_0': True,
  'actvsubs_fuzzy_0': True,
  'phones_fuzzy_0': True,
  'models_fuzzy_0': True,
  'eqpdays_fuzzy_1': True,
  'age1_fuzzy_1': True,
  'age2_fuzzy_2': True,
  'children_fuzzy_2': True,
  'credita_fuzzy_2': True,
  'creditaa_fuzzy_0': True,
  'prizmrur_fuzzy_0': True,
  'prizmub_fuzzy_0': True,
  'prizmtwn_fuzzy_0': True,
  'refurb_fuzzy_0': True,
  'webcap_fuzzy_1': True,
  'truck_fuzzy_0': True,
  'rv_fuzzy_0': True,
  'occprof_fuzzy_2': True,
  'occcler_fuzzy_0': True,
  'occcrft_fuzzy_0': True,
  'occstud_fuzzy_0': True,
  'occhmkr_fuzzy_0': True,
  'occret_fuzzy_0': True,
  'occself_fuzzy_0': True,
  'ownrent_fuzzy_0': True,
  'marryun_fuzzy_0': True,
  'marryyes_fuzzy_2': True,
  'mailord_fuzzy_0': True,
  'mailres_fuzzy_2': True,
  'mailflag_fuzzy_0': True,
  'travel_fuzzy_0': True,
  'pcown_fuzzy_2': True,
  'creditcd_fuzzy_1': True,
  'retcalls_fuzzy_0': True,
  'retaccpt_fuzzy_0': True,
  'newcelly_fuzzy_0': True,
  'newcelln_fuzzy_0': True,
  'refer_fuzzy_0': True,
  'incmiss_fuzzy_0': True,
  'income_fuzzy_1': True,
  'mcycle_fuzzy_0': True,
  'setprcm_fuzzy_1': True,
  'setprc_fuzzy_0': True,
  'retcall_fuzzy_0': True},
 'transaction4': {'revenue_fuzzy_1': True,
  'mou_fuzzy_1': True,
  'recchrge_fuzzy_1': True,
  'directas_fuzzy_1': True,
  'overage_fuzzy_1': True,
  'roam_fuzzy_1': True,
  'changem_fuzzy_1': True,
  'changer_fuzzy_1': True,
  'dropvce_fuzzy_1': True,
  'blckvce_fuzzy_1': True,
  'unansvce_fuzzy_1': True,
  'custcare_fuzzy_1': True,
  'threeway_fuzzy_1': True,
  'mourec_fuzzy_1': True,
  'outcalls_fuzzy_1': True,
  'incalls_fuzzy_1': True,
  'peakvce_fuzzy_1': True,
  'opeakvce_fuzzy_1': True,
  'dropblk_fuzzy_1': True,
  'callfwdv_fuzzy_0': True,
  'callwait_fuzzy_1': True,
  'months_fuzzy_1': True,
  'uniqsubs_fuzzy_0': True,
  'actvsubs_fuzzy_0': True,
  'phones_fuzzy_1': True,
  'models_fuzzy_1': True,
  'eqpdays_fuzzy_0': True,
  'age1_fuzzy_1': True,
  'age2_fuzzy_0': True,
  'children_fuzzy_0': True,
  'credita_fuzzy_0': True,
  'creditaa_fuzzy_0': True,
  'prizmrur_fuzzy_0': True,
  'prizmub_fuzzy_2': True,
  'prizmtwn_fuzzy_0': True,
  'refurb_fuzzy_0': True,
  'webcap_fuzzy_1': True,
  'truck_fuzzy_0': True,
  'rv_fuzzy_0': True,
  'occprof_fuzzy_0': True,
  'occcler_fuzzy_0': True,
  'occcrft_fuzzy_0': True,
  'occstud_fuzzy_0': True,
  'occhmkr_fuzzy_0': True,
  'occret_fuzzy_0': True,
  'occself_fuzzy_0': True,
  'ownrent_fuzzy_0': True,
  'marryun_fuzzy_0': True,
  'marryyes_fuzzy_2': True,
  'mailord_fuzzy_0': True,
  'mailres_fuzzy_0': True,
  'mailflag_fuzzy_0': True,
  'travel_fuzzy_0': True,
  'pcown_fuzzy_0': True,
  'creditcd_fuzzy_1': True,
  'retcalls_fuzzy_0': True,
  'retaccpt_fuzzy_0': True,
  'newcelly_fuzzy_0': True,
  'newcelln_fuzzy_0': True,
  'refer_fuzzy_0': True,
  'incmiss_fuzzy_0': True,
  'income_fuzzy_1': True,
  'mcycle_fuzzy_0': True,
  'setprcm_fuzzy_0': True,
  'setprc_fuzzy_1': True,
  'retcall_fuzzy_0': True},
 'transaction5': {'revenue_fuzzy_1': True,
  'mou_fuzzy_1': True,
  'recchrge_fuzzy_1': True,
  'directas_fuzzy_0': True,
  'overage_fuzzy_1': True,
  'roam_fuzzy_1': True,
  'changem_fuzzy_1': True,
  'changer_fuzzy_1': True,
  'dropvce_fuzzy_1': True,
  'blckvce_fuzzy_1': True,
  'unansvce_fuzzy_1': True,
  'custcare_fuzzy_1': True,
  'threeway_fuzzy_0': True,
  'mourec_fuzzy_1': True,
  'outcalls_fuzzy_1': True,
  'incalls_fuzzy_1': True,
  'peakvce_fuzzy_1': True,
  'opeakvce_fuzzy_1': True,
  'dropblk_fuzzy_1': True,
  'callfwdv_fuzzy_0': True,
  'callwait_fuzzy_1': True,
  'months_fuzzy_0': True,
  'uniqsubs_fuzzy_1': True,
  'actvsubs_fuzzy_1': True,
  'phones_fuzzy_0': True,
  'models_fuzzy_0': True,
  'eqpdays_fuzzy_1': True,
  'age1_fuzzy_1': True,
  'age2_fuzzy_1': True,
  'children_fuzzy_2': True,
  'credita_fuzzy_0': True,
  'creditaa_fuzzy_0': True,
  'prizmrur_fuzzy_0': True,
  'prizmub_fuzzy_2': True,
  'prizmtwn_fuzzy_0': True,
  'refurb_fuzzy_0': True,
  'webcap_fuzzy_1': True,
  'truck_fuzzy_2': True,
  'rv_fuzzy_0': True,
  'occprof_fuzzy_2': True,
  'occcler_fuzzy_0': True,
  'occcrft_fuzzy_0': True,
  'occstud_fuzzy_0': True,
  'occhmkr_fuzzy_0': True,
  'occret_fuzzy_0': True,
  'occself_fuzzy_0': True,
  'ownrent_fuzzy_0': True,
  'marryun_fuzzy_0': True,
  'marryyes_fuzzy_2': True,
  'mailord_fuzzy_2': True,
  'mailres_fuzzy_2': True,
  'mailflag_fuzzy_0': True,
  'travel_fuzzy_0': True,
  'pcown_fuzzy_2': True,
  'creditcd_fuzzy_1': True,
  'retcalls_fuzzy_0': True,
  'retaccpt_fuzzy_0': True,
  'newcelly_fuzzy_2': True,
  'newcelln_fuzzy_0': True,
  'refer_fuzzy_0': True,
  'incmiss_fuzzy_0': True,
  'income_fuzzy_1': True,
  'mcycle_fuzzy_0': True,
  'setprcm_fuzzy_1': True,
  'setprc_fuzzy_0': True,
  'retcall_fuzzy_0': True},
 'transaction6': {'revenue_fuzzy_1': True,
  'mou_fuzzy_0': True,
  'recchrge_fuzzy_1': True,
  'directas_fuzzy_0': True,
  'overage_fuzzy_0': True,
  'roam_fuzzy_0': True,
  'changem_fuzzy_1': True,
  'changer_fuzzy_1': True,
  'dropvce_fuzzy_0': True,
  'blckvce_fuzzy_0': True,
  'unansvce_fuzzy_0': True,
  'custcare_fuzzy_0': True,
  'threeway_fuzzy_0': True,
  'mourec_fuzzy_0': True,
  'outcalls_fuzzy_0': True,
  'incalls_fuzzy_0': True,
  'peakvce_fuzzy_0': True,
  'opeakvce_fuzzy_0': True,
  'dropblk_fuzzy_0': True,
  'callfwdv_fuzzy_0': True,
  'callwait_fuzzy_0': True,
  'months_fuzzy_1': True,
  'uniqsubs_fuzzy_0': True,
  'actvsubs_fuzzy_0': True,
  'phones_fuzzy_0': True,
  'models_fuzzy_0': True,
  'eqpdays_fuzzy_1': True,
  'age1_fuzzy_1': True,
  'age2_fuzzy_1': True,
  'children_fuzzy_2': True,
  'credita_fuzzy_0': True,
  'creditaa_fuzzy_0': True,
  'prizmrur_fuzzy_0': True,
  'prizmub_fuzzy_2': True,
  'prizmtwn_fuzzy_0': True,
  'refurb_fuzzy_0': True,
  'webcap_fuzzy_1': True,
  'truck_fuzzy_2': True,
  'rv_fuzzy_0': True,
  'occprof_fuzzy_2': True,
  'occcler_fuzzy_0': True,
  'occcrft_fuzzy_0': True,
  'occstud_fuzzy_0': True,
  'occhmkr_fuzzy_0': True,
  'occret_fuzzy_0': True,
  'occself_fuzzy_0': True,
  'ownrent_fuzzy_0': True,
  'marryun_fuzzy_0': True,
  'marryyes_fuzzy_2': True,
  'mailord_fuzzy_2': True,
  'mailres_fuzzy_2': True,
  'mailflag_fuzzy_0': True,
  'travel_fuzzy_0': True,
  'pcown_fuzzy_0': True,
  'creditcd_fuzzy_1': True,
  'retcalls_fuzzy_0': True,
  'retaccpt_fuzzy_0': True,
  'newcelly_fuzzy_0': True,
  'newcelln_fuzzy_0': True,
  'refer_fuzzy_0': True,
  'incmiss_fuzzy_0': True,
  'income_fuzzy_1': True,
  'mcycle_fuzzy_0': True,
  'setprcm_fuzzy_1': True,
  'setprc_fuzzy_0': True,
  'retcall_fuzzy_0': True},
 'transaction7': {'revenue_fuzzy_1': True,
  'mou_fuzzy_1': True,
  'recchrge_fuzzy_1': True,
  'directas_fuzzy_0': True,
  'overage_fuzzy_0': True,
  'roam_fuzzy_0': True,
  'changem_fuzzy_1': True,
  'changer_fuzzy_1': True,
  'dropvce_fuzzy_1': True,
  'blckvce_fuzzy_0': True,
  'unansvce_fuzzy_1': True,
  'custcare_fuzzy_0': True,
  'threeway_fuzzy_1': True,
  'mourec_fuzzy_0': True,
  'outcalls_fuzzy_1': True,
  'incalls_fuzzy_0': True,
  'peakvce_fuzzy_1': True,
  'opeakvce_fuzzy_1': True,
  'dropblk_fuzzy_0': True,
  'callfwdv_fuzzy_0': True,
  'callwait_fuzzy_1': True,
  'months_fuzzy_1': True,
  'uniqsubs_fuzzy_0': True,
  'actvsubs_fuzzy_0': True,
  'phones_fuzzy_1': True,
  'models_fuzzy_1': True,
  'eqpdays_fuzzy_0': True,
  'age1_fuzzy_1': True,
  'age2_fuzzy_1': True,
  'children_fuzzy_0': True,
  'credita_fuzzy_0': True,
  'creditaa_fuzzy_0': True,
  'prizmrur_fuzzy_0': True,
  'prizmub_fuzzy_0': True,
  'prizmtwn_fuzzy_0': True,
  'refurb_fuzzy_0': True,
  'webcap_fuzzy_1': True,
  'truck_fuzzy_0': True,
  'rv_fuzzy_0': True,
  'occprof_fuzzy_0': True,
  'occcler_fuzzy_0': True,
  'occcrft_fuzzy_0': True,
  'occstud_fuzzy_0': True,
  'occhmkr_fuzzy_0': True,
  'occret_fuzzy_0': True,
  'occself_fuzzy_0': True,
  'ownrent_fuzzy_0': True,
  'marryun_fuzzy_0': True,
  'marryyes_fuzzy_2': True,
  'mailord_fuzzy_0': True,
  'mailres_fuzzy_0': True,
  'mailflag_fuzzy_0': True,
  'travel_fuzzy_0': True,
  'pcown_fuzzy_2': True,
  'creditcd_fuzzy_1': True,
  'retcalls_fuzzy_0': True,
  'retaccpt_fuzzy_0': True,
  'newcelly_fuzzy_0': True,
  'newcelln_fuzzy_0': True,
  'refer_fuzzy_0': True,
  'incmiss_fuzzy_0': True,
  'income_fuzzy_1': True,
  'mcycle_fuzzy_0': True,
  'setprcm_fuzzy_0': True,
  'setprc_fuzzy_1': True,
  'retcall_fuzzy_0': True},
 'transaction8': {'revenue_fuzzy_1': True,
  'mou_fuzzy_1': True,
  'recchrge_fuzzy_1': True,
  'directas_fuzzy_0': True,
  'overage_fuzzy_0': True,
  'roam_fuzzy_0': True,
  'changem_fuzzy_1': True,
  'changer_fuzzy_1': True,
  'dropvce_fuzzy_0': True,
  'blckvce_fuzzy_0': True,
  'unansvce_fuzzy_0': True,
  'custcare_fuzzy_0': True,
  'threeway_fuzzy_0': True,
  'mourec_fuzzy_0': True,
  'outcalls_fuzzy_0': True,
  'incalls_fuzzy_0': True,
  'peakvce_fuzzy_0': True,
  'opeakvce_fuzzy_0': True,
  'dropblk_fuzzy_0': True,
  'callfwdv_fuzzy_0': True,
  'callwait_fuzzy_0': True,
  'months_fuzzy_0': True,
  'uniqsubs_fuzzy_0': True,
  'actvsubs_fuzzy_0': True,
  'phones_fuzzy_0': True,
  'models_fuzzy_0': True,
  'eqpdays_fuzzy_1': True,
  'age1_fuzzy_0': True,
  'age2_fuzzy_0': True,
  'children_fuzzy_0': True,
  'credita_fuzzy_0': True,
  'creditaa_fuzzy_0': True,
  'prizmrur_fuzzy_0': True,
  'prizmub_fuzzy_0': True,
  'prizmtwn_fuzzy_0': True,
  'refurb_fuzzy_0': True,
  'webcap_fuzzy_1': True,
  'truck_fuzzy_0': True,
  'rv_fuzzy_0': True,
  'occprof_fuzzy_0': True,
  'occcler_fuzzy_0': True,
  'occcrft_fuzzy_0': True,
  'occstud_fuzzy_0': True,
  'occhmkr_fuzzy_0': True,
  'occret_fuzzy_0': True,
  'occself_fuzzy_0': True,
  'ownrent_fuzzy_0': True,
  'marryun_fuzzy_0': True,
  'marryyes_fuzzy_0': True,
  'mailord_fuzzy_0': True,
  'mailres_fuzzy_0': True,
  'mailflag_fuzzy_0': True,
  'travel_fuzzy_0': True,
  'pcown_fuzzy_0': True,
  'creditcd_fuzzy_1': True,
  'retcalls_fuzzy_0': True,
  'retaccpt_fuzzy_0': True,
  'newcelly_fuzzy_0': True,
  'newcelln_fuzzy_2': True,
  'refer_fuzzy_0': True,
  'incmiss_fuzzy_0': True,
  'income_fuzzy_1': True,
  'mcycle_fuzzy_0': True,
  'setprcm_fuzzy_1': True,
  'setprc_fuzzy_0': True,
  'retcall_fuzzy_0': True},
 'transaction9': {'revenue_fuzzy_1': True,
  'mou_fuzzy_1': True,
  'recchrge_fuzzy_2': True,
  'directas_fuzzy_1': True,
  'overage_fuzzy_0': True,
  'roam_fuzzy_1': True,
  'changem_fuzzy_1': True,
  'changer_fuzzy_1': True,
  'dropvce_fuzzy_1': True,
  'blckvce_fuzzy_1': True,
  'unansvce_fuzzy_1': True,
  'custcare_fuzzy_0': True,
  'threeway_fuzzy_1': True,
  'mourec_fuzzy_1': True,
  'outcalls_fuzzy_1': True,
  'incalls_fuzzy_1': True,
  'peakvce_fuzzy_1': True,
  'opeakvce_fuzzy_1': True,
  'dropblk_fuzzy_1': True,
  'callfwdv_fuzzy_0': True,
  'callwait_fuzzy_1': True,
  'months_fuzzy_1': True,
  'uniqsubs_fuzzy_0': True,
  'actvsubs_fuzzy_0': True,
  'phones_fuzzy_0': True,
  'models_fuzzy_0': True,
  'eqpdays_fuzzy_1': True,
  'age1_fuzzy_1': True,
  'age2_fuzzy_1': True,
  'children_fuzzy_2': True,
  'credita_fuzzy_0': True,
  'creditaa_fuzzy_0': True,
  'prizmrur_fuzzy_0': True,
  'prizmub_fuzzy_0': True,
  'prizmtwn_fuzzy_0': True,
  'refurb_fuzzy_0': True,
  'webcap_fuzzy_1': True,
  'truck_fuzzy_0': True,
  'rv_fuzzy_0': True,
  'occprof_fuzzy_2': True,
  'occcler_fuzzy_0': True,
  'occcrft_fuzzy_0': True,
  'occstud_fuzzy_0': True,
  'occhmkr_fuzzy_0': True,
  'occret_fuzzy_0': True,
  'occself_fuzzy_0': True,
  'ownrent_fuzzy_0': True,
  'marryun_fuzzy_0': True,
  'marryyes_fuzzy_2': True,
  'mailord_fuzzy_2': True,
  'mailres_fuzzy_2': True,
  'mailflag_fuzzy_0': True,
  'travel_fuzzy_0': True,
  'pcown_fuzzy_2': True,
  'creditcd_fuzzy_1': True,
  'retcalls_fuzzy_0': True,
  'retaccpt_fuzzy_0': True,
  'newcelly_fuzzy_2': True,
  'newcelln_fuzzy_0': True,
  'refer_fuzzy_0': True,
  'incmiss_fuzzy_0': True,
  'income_fuzzy_1': True,
  'mcycle_fuzzy_0': True,
  'setprcm_fuzzy_1': True,
  'setprc_fuzzy_0': True,
  'retcall_fuzzy_0': True},
 'transaction10': {'revenue_fuzzy_0': True,
  'mou_fuzzy_1': True,
  'recchrge_fuzzy_0': True,
  'directas_fuzzy_1': True,
  'overage_fuzzy_0': True,
  'roam_fuzzy_1': True,
  'changem_fuzzy_1': True,
  'changer_fuzzy_1': True,
  'dropvce_fuzzy_1': True,
  'blckvce_fuzzy_1': True,
  'unansvce_fuzzy_1': True,
  'custcare_fuzzy_0': True,
  'threeway_fuzzy_0': True,
  'mourec_fuzzy_0': True,
  'outcalls_fuzzy_1': True,
  'incalls_fuzzy_0': True,
  'peakvce_fuzzy_1': True,
  'opeakvce_fuzzy_1': True,
  'dropblk_fuzzy_1': True,
  'callfwdv_fuzzy_0': True,
  'callwait_fuzzy_0': True,
  'months_fuzzy_1': True,
  'uniqsubs_fuzzy_1': True,
  'actvsubs_fuzzy_1': True,
  'phones_fuzzy_0': True,
  'models_fuzzy_0': True,
  'eqpdays_fuzzy_1': True,
  'age1_fuzzy_1': True,
  'age2_fuzzy_0': True,
  'children_fuzzy_0': True,
  'credita_fuzzy_0': True,
  'creditaa_fuzzy_0': True,
  'prizmrur_fuzzy_0': True,
  'prizmub_fuzzy_0': True,
  'prizmtwn_fuzzy_0': True,
  'refurb_fuzzy_0': True,
  'webcap_fuzzy_1': True,
  'truck_fuzzy_2': True,
  'rv_fuzzy_2': True,
  'occprof_fuzzy_0': True,
  'occcler_fuzzy_0': True,
  'occcrft_fuzzy_0': True,
  'occstud_fuzzy_0': True,
  'occhmkr_fuzzy_0': True,
  'occret_fuzzy_0': True,
  'occself_fuzzy_0': True,
  'ownrent_fuzzy_0': True,
  'marryun_fuzzy_2': True,
  'marryyes_fuzzy_0': True,
  'mailord_fuzzy_2': True,
  'mailres_fuzzy_2': True,
  'mailflag_fuzzy_0': True,
  'travel_fuzzy_0': True,
  'pcown_fuzzy_0': True,
  'creditcd_fuzzy_1': True,
  'retcalls_fuzzy_0': True,
  'retaccpt_fuzzy_0': True,
  'newcelly_fuzzy_0': True,
  'newcelln_fuzzy_0': True,
  'refer_fuzzy_0': True,
  'incmiss_fuzzy_0': True,
  'income_fuzzy_1': True,
  'mcycle_fuzzy_0': True,
  'setprcm_fuzzy_1': True,
  'setprc_fuzzy_0': True,
  'retcall_fuzzy_0': True},
 'transaction11': {'revenue_fuzzy_1': True,
  'mou_fuzzy_1': True,
  'recchrge_fuzzy_1': True,
  'directas_fuzzy_0': True,
  'overage_fuzzy_1': True,
  'roam_fuzzy_1': True,
  'changem_fuzzy_1': True,
  'changer_fuzzy_1': True,
  'dropvce_fuzzy_0': True,
  'blckvce_fuzzy_0': True,
  'unansvce_fuzzy_0': True,
  'custcare_fuzzy_0': True,
  'threeway_fuzzy_0': True,
  'mourec_fuzzy_0': True,
  'outcalls_fuzzy_0': True,
  'incalls_fuzzy_0': True,
  'peakvce_fuzzy_0': True,
  'opeakvce_fuzzy_0': True,
  'dropblk_fuzzy_0': True,
  'callfwdv_fuzzy_0': True,
  'callwait_fuzzy_0': True,
  'months_fuzzy_0': True,
  'uniqsubs_fuzzy_0': True,
  'actvsubs_fuzzy_0': True,
  'phones_fuzzy_0': True,
  'models_fuzzy_0': True,
  'eqpdays_fuzzy_1': True,
  'age1_fuzzy_1': True,
  'age2_fuzzy_2': True,
  'children_fuzzy_2': True,
  'credita_fuzzy_0': True,
  'creditaa_fuzzy_0': True,
  'prizmrur_fuzzy_0': True,
  'prizmub_fuzzy_2': True,
  'prizmtwn_fuzzy_0': True,
  'refurb_fuzzy_0': True,
  'webcap_fuzzy_1': True,
  'truck_fuzzy_0': True,
  'rv_fuzzy_0': True,
  'occprof_fuzzy_0': True,
  'occcler_fuzzy_0': True,
  'occcrft_fuzzy_0': True,
  'occstud_fuzzy_0': True,
  'occhmkr_fuzzy_0': True,
  'occret_fuzzy_0': True,
  'occself_fuzzy_0': True,
  'ownrent_fuzzy_0': True,
  'marryun_fuzzy_0': True,
  'marryyes_fuzzy_2': True,
  'mailord_fuzzy_2': True,
  'mailres_fuzzy_2': True,
  'mailflag_fuzzy_0': True,
  'travel_fuzzy_0': True,
  'pcown_fuzzy_0': True,
  'creditcd_fuzzy_1': True,
  'retcalls_fuzzy_0': True,
  'retaccpt_fuzzy_0': True,
  'newcelly_fuzzy_0': True,
  'newcelln_fuzzy_0': True,
  'refer_fuzzy_0': True,
  'incmiss_fuzzy_0': True,
  'income_fuzzy_2': True,
  'mcycle_fuzzy_0': True,
  'setprcm_fuzzy_1': True,
  'setprc_fuzzy_0': True,
  'retcall_fuzzy_0': True},
 'transaction12': {'revenue_fuzzy_1': True,
  'mou_fuzzy_2': True,
  'recchrge_fuzzy_1': True,
  'directas_fuzzy_0': True,
  'overage_fuzzy_0': True,
  'roam_fuzzy_0': True,
  'changem_fuzzy_1': True,
  'changer_fuzzy_1': True,
  'dropvce_fuzzy_1': True,
  'blckvce_fuzzy_1': True,
  'unansvce_fuzzy_1': True,
  'custcare_fuzzy_1': True,

### High Utility fuzzy Churn Patterns

In [31]:
import time

def extract_base_name(fuzzy_name):
    if fuzzy_name.startswith("Status_"):
        return "Status"
    elif fuzzy_name.startswith("Age Group_"):
        return "Age Group"
    elif fuzzy_name.startswith("Tariff Plan_"):
        return "Tariff Plan"
    elif "fuzzy" in fuzzy_name:
        return fuzzy_name.split("_", 1)[0]
    else:
        return fuzzy_name

def calculate_utility(itemset, transactions, profit_table):
    total_utility = 0
    for transaction in transactions.values():
        if set(itemset).issubset(set(transaction.keys())):
            for item, utility in transaction.items():
                if item in itemset:
                    base_name = extract_base_name(item)
                    total_utility += utility * profit_table.get(base_name, 0)
    return total_utility

def find_top_k_high_utility_itemsets(transactions, profit_table, k):
    itemsets = set()
    for transaction in transactions.values():
        itemsets.update(transaction.keys())

    high_utility_itemsets = {}
    for item in itemsets:
        utility = calculate_utility([item], transactions, profit_table)
        if utility > 0:
            high_utility_itemsets[(item,)] = utility

    P_itemsets = {}
    while True:
        temp_itemsets = {}
        for itemset, utility in high_utility_itemsets.items():
            for item in itemsets:
                if item not in itemset:
                    new_itemset = tuple(sorted(list(itemset) + [item]))
                    new_utility = calculate_utility(new_itemset, transactions, profit_table)
                    if new_utility > 0:
                        temp_itemsets[new_itemset] = new_utility
                        P_itemsets[new_itemset] = new_utility

        if not temp_itemsets:
            break

        sorted_itemsets = sorted(temp_itemsets.items(), key=lambda x: x[1], reverse=True)
        top_k_itemsets = sorted_itemsets[:k]
        high_utility_itemsets = {itemset: utility for itemset, utility in top_k_itemsets}

    return high_utility_itemsets, P_itemsets

def find_top_k_high_utility_itemsets(transactions, profit_table, k, desired_length):
    """
    Tìm ra K tập mục có độ hữu ích cao nhất với độ dài tối đa được chỉ định.
    """
    itemsets = set()
    for transaction in transactions.values():
        # Thêm từng mục trong giao dịch vào tập hợp itemsets
        itemsets.update(transaction.keys())

    # Lưu trữ các tập mục có độ hữu ích cao và tổng giá trị của chúng
    high_utility_itemsets = {}
    P_itemsets = {}

    for item in itemsets:
        utility = calculate_utility([item], transactions, profit_table)
        if utility > 0:
            high_utility_itemsets[(item,)] = utility

    while True:
        temp_itemsets = {}
        for itemset, utility in high_utility_itemsets.items():
            for item in itemsets:
                if item not in itemset:
                    # Tạo tập mục mới bằng cách kết hợp
                    new_itemset = tuple(sorted(list(itemset) + [item]))
                    new_utility = calculate_utility(new_itemset, transactions, profit_table)

                    # Kiểm tra điều kiện độ dài và độ hữu ích
                    if new_utility > 0 and len(new_itemset) <= desired_length:
                        temp_itemsets[new_itemset] = new_utility
                        P_itemsets[new_itemset] = new_utility

        if not temp_itemsets:
            break

        # Lấy top K tập mục có độ hữu ích cao nhất
        sorted_itemsets = sorted(temp_itemsets.items(), key=lambda x: x[1], reverse=True)
        top_k_itemsets = sorted_itemsets[:k]
        high_utility_itemsets = {itemset: utility for itemset, utility in top_k_itemsets}

    return high_utility_itemsets, P_itemsets

In [32]:
result,P_itemsets= find_top_k_high_utility_itemsets(filtered_transactions, profit_table, 3,2)


sorted_data = sorted(P_itemsets.items(), key=lambda x: x[1], reverse=True)


top_10 = sorted_data[:10]
top_10 = {itemset: value for itemset, value in top_10}

print("Top 10 High Utility Itemsets:")
for itemset, utility in top_10.items():
    print(itemset, "-> Utility:", round(utility,0))

Top 10 High Utility Itemsets:
('changem_fuzzy_1', 'eqpdays_fuzzy_1') -> Utility: 1902.0
('eqpdays_fuzzy_1', 'months_fuzzy_1') -> Utility: 1609.0
('creditaa_fuzzy_0', 'eqpdays_fuzzy_1') -> Utility: 1506.0
('eqpdays_fuzzy_1', 'mou_fuzzy_1') -> Utility: 1493.0
('changer_fuzzy_1', 'eqpdays_fuzzy_1') -> Utility: 1457.0
('eqpdays_fuzzy_1', 'recchrge_fuzzy_1') -> Utility: 1428.0
('eqpdays_fuzzy_1', 'webcap_fuzzy_1') -> Utility: 1350.0
('credita_fuzzy_0', 'eqpdays_fuzzy_1') -> Utility: 1349.0
('eqpdays_fuzzy_1', 'retcalls_fuzzy_0') -> Utility: 1346.0
('changem_fuzzy_1', 'months_fuzzy_1') -> Utility: 1324.0

In [33]:

fuzzy_df = pd.DataFrame()
for feature in Xtofuzzy_Tri.columns:
    min_val = Xtofuzzy_Tri[feature].min()
    median_val = Xtofuzzy_Tri[feature].quantile(0.5)
    max_val = Xtofuzzy_Tri[feature].max()

    fuzzy_df[f'{feature}_fuzzy'] = Xtofuzzy_Tri[feature].apply(lambda x: fuzzy_classification(x, min_val, median_val, max_val))


df_fuzzy = fuzzy_df

fuzzy_columns = [col for col in df_fuzzy.columns]

df_fuzzy = pd.get_dummies(df_fuzzy, columns=fuzzy_columns)
df_fuzzy =df_fuzzy.astype(int)
df_fuzzy

,revenue_fuzzy_0,revenue_fuzzy_1,revenue_fuzzy_2,mou_fuzzy_0,mou_fuzzy_1,mou_fuzzy_2,recchrge_fuzzy_0,recchrge_fuzzy_1,recchrge_fuzzy_2,directas_fuzzy_0,...,income_fuzzy_2,mcycle_fuzzy_0,mcycle_fuzzy_2,setprcm_fuzzy_0,setprcm_fuzzy_1,setprc_fuzzy_0,setprc_fuzzy_1,setprc_fuzzy_2,retcall_fuzzy_0,retcall_fuzzy_2
54569,0,1,0,0,1,0,0,1,0,1,...,0,0,1,0,1,1,0,0,1,0
52439,0,1,0,0,1,0,0,1,0,1,...,0,1,0,1,0,0,1,0,1,0
63639,0,1,0,1,0,0,0,1,0,1,...,0,1,0,0,1,1,0,0,1,0
57383,0,1,0,0,1,0,0,1,0,0,...,0,1,0,1,0,0,1,0,1,0
70085,0,1,0,0,1,0,0,1,0,1,...,0,1,0,0,1,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55990,0,1,0,0,1,0,0,1,0,1,...,0,1,0,0,1,1,0,0,1,0
53067,0,1,0,1,0,0,0,1,0,1,...,1,1,0,0,1,1,0,0,1,0
53682,0,1,0,0,1,0,0,1,0,1,...,0,1,0,1,0,0,1,0,1,0
51952,0,1,0,0,1,0,0,1,0,1,...,1,1,0,1,0,0,1,0,1,0
58158,0,1,0,0,1,0,0,1,0,1,...,0,1,0,1,0,0,1,0,1,0

In [34]:
Xy_merge = pd.merge(X_temp_test, df_fuzzy, left_index=True, right_index=True, how='left')
Xy_merge['fuzzyp1'] = Xy_merge['changem_fuzzy_1'] * Xy_merge['eqpdays_fuzzy_1']
Xy_merge['fuzzyp2'] = Xy_merge['eqpdays_fuzzy_1'] * Xy_merge['months_fuzzy_1']
Xy_merge['fuzzyp3'] = Xy_merge['creditaa_fuzzy_0'] * Xy_merge['eqpdays_fuzzy_1']
Xy_merge['fuzzyp4'] = Xy_merge['eqpdays_fuzzy_1'] * Xy_merge['mou_fuzzy_1']
Xy_merge['fuzzyp5'] = Xy_merge['actvsubs_fuzzy_1'] * Xy_merge['eqpdays_fuzzy_1']
Xy_merge['fuzzyp6'] = Xy_merge['eqpdays_fuzzy_1'] * Xy_merge['recchrge_fuzzy_1']
Xy_merge['fuzzyp7'] = Xy_merge['changer_fuzzy_1'] * Xy_merge['eqpdays_fuzzy_1']
Xy_merge['fuzzyp8'] = Xy_merge['changem_fuzzy_1'] * Xy_merge['months_fuzzy_1']
Xy_merge['fuzzyp9'] = Xy_merge['eqpdays_fuzzy_1'] * Xy_merge['webcap_fuzzy_1']
Xy_merge['fuzzyp10'] = Xy_merge['credita_fuzzy_0'] * Xy_merge['eqpdays_fuzzy_1']

print(Xy_merge.columns.tolist())

['revenue', 'mou', 'recchrge', 'directas', 'overage', 'roam', 'changem', 'changer', 'dropvce', 'blckvce', 'unansvce', 'custcare', 'threeway', 'mourec', 'outcalls', 'incalls', 'peakvce', 'opeakvce', 'dropblk', 'callfwdv', 'callwait', 'months', 'uniqsubs', 'actvsubs', 'phones', 'models', 'eqpdays', 'age1', 'age2', 'children', 'credita', 'creditaa', 'prizmrur', 'prizmub', 'prizmtwn', 'refurb', 'webcap', 'truck', 'rv', 'occprof', 'occcler', 'occcrft', 'occstud', 'occhmkr', 'occret', 'occself', 'ownrent', 'marryun', 'marryyes', 'mailord', 'mailres', 'mailflag', 'travel', 'pcown', 'creditcd', 'retcalls', 'retaccpt', 'newcelly', 'newcelln', 'refer', 'incmiss', 'income', 'mcycle', 'setprcm', 'setprc', 'retcall', 'churn', 'revenue_fuzzy_0', 'revenue_fuzzy_1', 'revenue_fuzzy_2', 'mou_fuzzy_0', 'mou_fuzzy_1', 'mou_fuzzy_2', 'recchrge_fuzzy_0', 'recchrge_fuzzy_1', 'recchrge_fuzzy_2', 'directas_fuzzy_0', 'directas_fuzzy_1', 'directas_fuzzy_2', 'overage_fuzzy_0', 'overage_fuzzy_1', 'overage_fuzzy_2', 'roam_fuzzy_0', 'roam_fuzzy_1', 'roam_fuzzy_2', 'changem_fuzzy_0', 'changem_fuzzy_1', 'changem_fuzzy_2', 'changer_fuzzy_0', 'changer_fuzzy_1', 'changer_fuzzy_2', 'dropvce_fuzzy_0', 'dropvce_fuzzy_1', 'dropvce_fuzzy_2', 'blckvce_fuzzy_0', 'blckvce_fuzzy_1', 'blckvce_fuzzy_2', 'unansvce_fuzzy_0', 'unansvce_fuzzy_1', 'unansvce_fuzzy_2', 'custcare_fuzzy_0', 'custcare_fuzzy_1', 'custcare_fuzzy_2', 'threeway_fuzzy_0', 'threeway_fuzzy_1', 'threeway_fuzzy_2', 'mourec_fuzzy_0', 'mourec_fuzzy_1', 'mourec_fuzzy_2', 'outcalls_fuzzy_0', 'outcalls_fuzzy_1', 'outcalls_fuzzy_2', 'incalls_fuzzy_0', 'incalls_fuzzy_1', 'incalls_fuzzy_2', 'peakvce_fuzzy_0', 'peakvce_fuzzy_1', 'peakvce_fuzzy_2', 'opeakvce_fuzzy_0', 'opeakvce_fuzzy_1', 'opeakvce_fuzzy_2', 'dropblk_fuzzy_0', 'dropblk_fuzzy_1', 'dropblk_fuzzy_2', 'callfwdv_fuzzy_0', 'callfwdv_fuzzy_1', 'callfwdv_fuzzy_2', 'callwait_fuzzy_0', 'callwait_fuzzy_1', 'callwait_fuzzy_2', 'months_fuzzy_0', 'months_fuzzy_1', 'months_fuzzy_2', 'uniqsubs_fuzzy_0', 'uniqsubs_fuzzy_1', 'uniqsubs_fuzzy_2', 'actvsubs_fuzzy_0', 'actvsubs_fuzzy_1', 'actvsubs_fuzzy_2', 'phones_fuzzy_0', 'phones_fuzzy_1', 'phones_fuzzy_2', 'models_fuzzy_0', 'models_fuzzy_1', 'models_fuzzy_2', 'eqpdays_fuzzy_0', 'eqpdays_fuzzy_1', 'eqpdays_fuzzy_2', 'age1_fuzzy_0', 'age1_fuzzy_1', 'age1_fuzzy_2', 'age2_fuzzy_0', 'age2_fuzzy_1', 'age2_fuzzy_2', 'children_fuzzy_0', 'children_fuzzy_2', 'credita_fuzzy_0', 'credita_fuzzy_2', 'creditaa_fuzzy_0', 'creditaa_fuzzy_2', 'prizmrur_fuzzy_0', 'prizmrur_fuzzy_2', 'prizmub_fuzzy_0', 'prizmub_fuzzy_2', 'prizmtwn_fuzzy_0', 'prizmtwn_fuzzy_2', 'refurb_fuzzy_0', 'refurb_fuzzy_2', 'webcap_fuzzy_0', 'webcap_fuzzy_1', 'truck_fuzzy_0', 'truck_fuzzy_2', 'rv_fuzzy_0', 'rv_fuzzy_2', 'occprof_fuzzy_0', 'occprof_fuzzy_2', 'occcler_fuzzy_0', 'occcler_fuzzy_2', 'occcrft_fuzzy_0', 'occcrft_fuzzy_2', 'occstud_fuzzy_0', 'occstud_fuzzy_2', 'occhmkr_fuzzy_0', 'occhmkr_fuzzy_2', 'occret_fuzzy_0', 'occret_fuzzy_2', 'occself_fuzzy_0', 'occself_fuzzy_2', 'ownrent_fuzzy_0', 'ownrent_fuzzy_2', 'marryun_fuzzy_0', 'marryun_fuzzy_2', 'marryyes_fuzzy_0', 'marryyes_fuzzy_2', 'mailord_fuzzy_0', 'mailord_fuzzy_2', 'mailres_fuzzy_0', 'mailres_fuzzy_2', 'mailflag_fuzzy_0', 'mailflag_fuzzy_2', 'travel_fuzzy_0', 'travel_fuzzy_2', 'pcown_fuzzy_0', 'pcown_fuzzy_2', 'creditcd_fuzzy_0', 'creditcd_fuzzy_1', 'retcalls_fuzzy_0', 'retcalls_fuzzy_1', 'retcalls_fuzzy_2', 'retaccpt_fuzzy_0', 'retaccpt_fuzzy_1', 'retaccpt_fuzzy_2', 'newcelly_fuzzy_0', 'newcelly_fuzzy_2', 'newcelln_fuzzy_0', 'newcelln_fuzzy_2', 'refer_fuzzy_0', 'refer_fuzzy_1', 'refer_fuzzy_2', 'incmiss_fuzzy_0', 'incmiss_fuzzy_2', 'income_fuzzy_0', 'income_fuzzy_1', 'income_fuzzy_2', 'mcycle_fuzzy_0', 'mcycle_fuzzy_2', 'setprcm_fuzzy_0', 'setprcm_fuzzy_1', 'setprc_fuzzy_0', 'setprc_fuzzy_1', 'setprc_fuzzy_2', 'retcall_fuzzy_0', 'retcall_fuzzy_2', 'fuzzyp1', 'fuzzyp2', 'fuzzyp3', 'fuzzyp4', 'fuzzyp5', 'fuzzyp6', 'fuzzyp7', 'fuzzyp8', 'fuzzyp9', 'fuzzyp10']

In [35]:
Xy_merge = Xy_merge.fillna(0)

In [36]:
columns_to_keep = [
    'revenue', 'mou', 'recchrge', 'directas', 'overage', 'roam', 'changem', 'changer',
    'dropvce', 'blckvce', 'unansvce', 'custcare', 'threeway', 'mourec', 'outcalls', 'incalls',
    'peakvce', 'opeakvce', 'dropblk', 'callfwdv', 'callwait', 'months', 'uniqsubs', 'actvsubs',
    'phones', 'models', 'eqpdays', 'age1', 'age2', 'children', 'credita', 'creditaa', 'prizmrur',
    'prizmub', 'prizmtwn', 'refurb', 'webcap', 'truck', 'rv', 'occprof', 'occcler', 'occcrft',
    'occstud', 'occhmkr', 'occret', 'occself', 'ownrent', 'marryun', 'marryyes', 'mailord',
    'mailres', 'mailflag', 'travel', 'pcown', 'creditcd', 'retcalls', 'retaccpt', 'newcelly',
    'newcelln', 'refer', 'incmiss', 'income', 'mcycle', 'setprcm', 'setprc', 'retcall',
    'fuzzyp1', 'fuzzyp2', 'fuzzyp3', 'fuzzyp4', 'fuzzyp5', 'fuzzyp6', 'fuzzyp7', 'fuzzyp8',
    'fuzzyp9', 'fuzzyp10'
]
X_test_2 = Xy_merge[columns_to_keep]
y_test_2 = Xy_merge['churn']

# Final Model

In [37]:
import xgboost as xgb
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import (accuracy_score, precision_score, recall_score,
                             f1_score, matthews_corrcoef, confusion_matrix, classification_report)
import time
from sklearn.metrics import roc_auc_score, roc_curve
import matplotlib.pyplot as plt
from imblearn.over_sampling import SMOTE
import optuna


overall_start_time = time.time()


smote = SMOTE(random_state=42)
X_resampled_2, y_resampled_2 = smote.fit_resample(X_train_2, y_train_2)

def objective(trial):
    """Hàm mục tiêu của Optuna để tìm siêu tham số tối ưu."""
    max_depth = trial.suggest_int('max_depth', 2, 10)
    learning_rate = trial.suggest_float('learning_rate', 0.01, 0.3)
    n_estimators = trial.suggest_int('n_estimators', 100, 500)

    model = xgb.XGBClassifier(
        objective='binary:logistic',
        max_depth=max_depth,
        learning_rate=learning_rate,
        n_estimators=n_estimators,
        verbosity=0,
        use_label_encoder=False
    )

    model.fit(X_resampled_2, y_resampled_2)
    y_prob_2 = model.predict_proba(X_test_2)[:, 1]

    return roc_auc_score(y_test_2, y_prob_2)

start_time = time.time()

# Thiết lập Optuna để tìm kiếm siêu tham số
study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=200)


end_time = time.time()

total_time = end_time - start_time
print(f"Thời gian tìm kiếm siêu tham số: {total_time:.2f} giây")

best_params = study.best_params
print("Siêu tham số tốt nhất:", best_params)

best_model = xgb.XGBClassifier(
    objective='binary:logistic',
    max_depth=best_params['max_depth'],
    learning_rate=best_params['learning_rate'],
    n_estimators=best_params['n_estimators'],
    verbosity=0,
    use_label_encoder=False
)
best_model.fit(X_train_2, y_train_2)

y_pred = best_model.predict(X_test_2)
y_prob = best_model.predict_proba(X_test_2)[:, 1]

auc_score = roc_auc_score(y_test_2, y_prob)
print("AUC:", auc_score)
print("Accuracy:", accuracy_score(y_test_2, y_pred))
print("Precision:", precision_score(y_test_2, y_pred))
print("Recall:", recall_score(y_test_2, y_pred))
print("F1 Score:", f1_score(y_test_2, y_pred))
print("Matthews Correlation Coefficient:", matthews_corrcoef(y_test_2, y_pred))
print("\nMa trận nhầm lẫn:")
print(confusion_matrix(y_test_2, y_pred))
print("\nBáo cáo phân loại:")
print(classification_report(y_test_2, y_pred))

# Ghi lại thời gian kết thúc toàn bộ quá trình
overall_end_time = time.time()

# Tính tổng thời gian thực thi
overall_total_time = overall_end_time - overall_start_time
print(f"Tổng thời gian thực thi: {overall_total_time:.2f} giây")

[I 2025-12-15 23:07:17,618] A new study created in memory with name: no-name-8a41e993-1fa1-4dd7-9f75-786e0bc1e903
[I 2025-12-15 23:07:17,973] Trial 0 finished with value: 0.9971058501322028 and parameters: {'max_depth': 2, 'learning_rate': 0.061839898830968465, 'n_estimators': 317}. Best is trial 0 with value: 0.9971058501322028.
[I 2025-12-15 23:07:18,585] Trial 1 finished with value: 0.9971138333461816 and parameters: {'max_depth': 7, 'learning_rate': 0.04187150526326223, 'n_estimators': 285}. Best is trial 1 with value: 0.9971138333461816.
[I 2025-12-15 23:07:19,295] Trial 2 finished with value: 0.9970482669178584 and parameters: {'max_depth': 4, 'learning_rate': 0.2628971215459385, 'n_estimators': 447}. Best is trial 1 with value: 0.9971138333461816.
[I 2025-12-15 23:07:19,658] Trial 3 finished with value: 0.997554623523432 and parameters: {'max_depth': 2, 'learning_rate': 0.1831270164970193, 'n_estimators': 315}. Best is trial 3 with value: 0.997554623523432.
[I 2025-12-15 23:07:19,984] Trial 4 finished with value: 0.9956051328232925 and parameters: {'max_depth': 5, 'learning_rate': 0.025359958867026557, 'n_estimators': 175}. Best is trial 3 with value: 0.997554623523432.
[I 2025-12-15 23:07:20,648] Trial 5 finished with value: 0.9971852888226551 and parameters: {'max_depth': 4, 'learning_rate': 0.18743923809103777, 'n_estimators': 436}. Best is trial 3 with value: 0.997554623523432.
[I 2025-12-15 23:07:21,507] Trial 6 finished with value: 0.996430652993143 and parameters: {'max_depth': 10, 'learning_rate': 0.21099936195019123, 'n_estimators': 270}. Best is trial 3 with value: 0.997554623523432.
[I 2025-12-15 23:07:21,857] Trial 7 finished with value: 0.9968482169675611 and parameters: {'max_depth': 5, 'learning_rate': 0.26199509257090187, 'n_estimators': 179}. Best is trial 3 with value: 0.997554623523432.
[I 2025-12-15 23:07:23,011] Trial 8 finished with value: 0.9965890988489677 and parameters: {'max_depth': 10, 'learning_rate': 0.15586964643420184, 'n_estimators': 381}. Best is trial 3 with value: 0.997554623523432.
[I 2025-12-15 23:07:24,334] Trial 9 finished with value: 0.9960692634306025 and parameters: {'max_depth': 9, 'learning_rate': 0.2966586217448078, 'n_estimators': 451}. Best is trial 3 with value: 0.997554623523432.
[I 2025-12-15 23:07:24,495] Trial 10 finished with value: 0.996797804684692 and parameters: {'max_depth': 2, 'learning_rate': 0.11886668836441514, 'n_estimators': 102}. Best is trial 3 with value: 0.997554623523432.
[I 2025-12-15 23:07:24,985] Trial 11 finished with value: 0.9973963045867487 and parameters: {'max_depth': 3, 'learning_rate': 0.17613050759343837, 'n_estimators': 381}. Best is trial 3 with value: 0.997554623523432.
[I 2025-12-15 23:07:25,400] Trial 12 finished with value: 0.9973322358042909 and parameters: {'max_depth': 2, 'learning_rate': 0.11018737866860215, 'n_estimators': 379}. Best is trial 3 with value: 0.997554623523432.
[I 2025-12-15 23:07:25,857] Trial 13 finished with value: 0.9973623917922306 and parameters: {'max_depth': 3, 'learning_rate': 0.20632857425999693, 'n_estimators': 350}. Best is trial 3 with value: 0.997554623523432.
[I 2025-12-15 23:07:26,355] Trial 14 finished with value: 0.9966849481843721 and parameters: {'max_depth': 6, 'learning_rate': 0.15250687389743153, 'n_estimators': 229}. Best is trial 3 with value: 0.997554623523432.
[I 2025-12-15 23:07:26,965] Trial 15 finished with value: 0.997556781148832 and parameters: {'max_depth': 3, 'learning_rate': 0.09335438926868898, 'n_estimators': 500}. Best is trial 15 with value: 0.997556781148832.
[I 2025-12-15 23:07:28,096] Trial 16 finished with value: 0.996778436823751 and parameters: {'max_depth': 7, 'learning_rate': 0.08501639826412809, 'n_estimators': 492}. Best is trial 15 with value: 0.997556781148832.
[I 2025-12-15 23:07:28,728] Trial 17 finished with value: 0.9975069019263559 and parameters: {'max_depth': 3, 'learning_rate': 0.11016309785088627, 'n_estimators': 485}. Best is trial 15 with value: 0.997556781148832.
[I 2025-12-15 23:07:29,069] Trial 18 finished with value: 0.9951170398821317 and parameters: {'max_depth': 4, 'learning_rate': 0.010979772397400667, 'n_estimators': 213}. Best is trial 15 with value: 0.997556781148832.
[I 2025-12-15 23:07:29,246] Trial 19 finished with value: 0.9970415021276344 and parameters: {'max_depth': 2, 'learning_rate': 0.13928804145023552, 'n_estimators': 121}. Best is trial 15 with value: 0.997556781148832.
[I 2025-12-15 23:07:29,836] Trial 20 finished with value: 0.9973236814541765 and parameters: {'max_depth': 5, 'learning_rate': 0.07283613034944894, 'n_estimators': 323}. Best is trial 15 with value: 0.997556781148832.
[I 2025-12-15 23:07:30,510] Trial 21 finished with value: 0.9975272089889415 and parameters: {'max_depth': 3, 'learning_rate': 0.10077929914211205, 'n_estimators': 490}. Best is trial 15 with value: 0.997556781148832.
[I 2025-12-15 23:07:31,112] Trial 22 finished with value: 0.9975752605757849 and parameters: {'max_depth': 3, 'learning_rate': 0.09071170327375572, 'n_estimators': 425}. Best is trial 22 with value: 0.9975752605757849.
[I 2025-12-15 23:07:31,765] Trial 23 finished with value: 0.9976080564818608 and parameters: {'max_depth': 4, 'learning_rate': 0.05443640925054569, 'n_estimators': 416}. Best is trial 23 with value: 0.9976080564818608.
[I 2025-12-15 23:07:32,438] Trial 24 finished with value: 0.9976095795115547 and parameters: {'max_depth': 4, 'learning_rate': 0.039226650124755985, 'n_estimators': 418}. Best is trial 24 with value: 0.9976095795115547.
[I 2025-12-15 23:07:33,094] Trial 25 finished with value: 0.9976274497266301 and parameters: {'max_depth': 4, 'learning_rate': 0.05104374116077658, 'n_estimators': 414}. Best is trial 25 with value: 0.9976274497266301.
[I 2025-12-15 23:07:33,910] Trial 26 finished with value: 0.9969765576031026 and parameters: {'max_depth': 6, 'learning_rate': 0.04883032720326258, 'n_estimators': 408}. Best is trial 25 with value: 0.9976274497266301.
[I 2025-12-15 23:07:34,523] Trial 27 finished with value: 0.9973513752107777 and parameters: {'max_depth': 5, 'learning_rate': 0.032815931996130025, 'n_estimators': 349}. Best is trial 25 with value: 0.9976274497266301.
[I 2025-12-15 23:07:35,156] Trial 28 finished with value: 0.9975978775667398 and parameters: {'max_depth': 4, 'learning_rate': 0.06778154000460652, 'n_estimators': 406}. Best is trial 25 with value: 0.9976274497266301.
[I 2025-12-15 23:07:36,225] Trial 29 finished with value: 0.9968855311950623 and parameters: {'max_depth': 7, 'learning_rate': 0.058813235899526695, 'n_estimators': 462}. Best is trial 25 with value: 0.9976274497266301.
[I 2025-12-15 23:07:36,912] Trial 30 finished with value: 0.995148135071716 and parameters: {'max_depth': 6, 'learning_rate': 0.010754971838220589, 'n_estimators': 356}. Best is trial 25 with value: 0.9976274497266301.
[I 2025-12-15 23:07:37,530] Trial 31 finished with value: 0.9976132601666484 and parameters: {'max_depth': 4, 'learning_rate': 0.06180932574011806, 'n_estimators': 402}. Best is trial 25 with value: 0.9976274497266301.
[I 2025-12-15 23:07:38,142] Trial 32 finished with value: 0.9975936638512531 and parameters: {'max_depth': 4, 'learning_rate': 0.049780968645387134, 'n_estimators': 412}. Best is trial 25 with value: 0.9976274497266301.
[I 2025-12-15 23:07:38,943] Trial 33 finished with value: 0.9973759213726782 and parameters: {'max_depth': 5, 'learning_rate': 0.02651239023453739, 'n_estimators': 463}. Best is trial 25 with value: 0.9976274497266301.
[I 2025-12-15 23:07:39,532] Trial 34 finished with value: 0.9975660716299648 and parameters: {'max_depth': 4, 'learning_rate': 0.07366643120318965, 'n_estimators': 394}. Best is trial 25 with value: 0.9976274497266301.
[I 2025-12-15 23:07:40,091] Trial 35 finished with value: 0.9971823696824084 and parameters: {'max_depth': 6, 'learning_rate': 0.03998692017628861, 'n_estimators': 285}. Best is trial 25 with value: 0.9976274497266301.
[I 2025-12-15 23:07:40,751] Trial 36 finished with value: 0.9976162554583798 and parameters: {'max_depth': 4, 'learning_rate': 0.059925347148255884, 'n_estimators': 435}. Best is trial 25 with value: 0.9976274497266301.
[I 2025-12-15 23:07:41,521] Trial 37 finished with value: 0.9973285043815407 and parameters: {'max_depth': 5, 'learning_rate': 0.07870519712885901, 'n_estimators': 439}. Best is trial 25 with value: 0.9976274497266301.
[I 2025-12-15 23:07:42,327] Trial 38 finished with value: 0.997002626794697 and parameters: {'max_depth': 8, 'learning_rate': 0.02509427953152315, 'n_estimators': 327}. Best is trial 25 with value: 0.9976274497266301.
[I 2025-12-15 23:07:43,084] Trial 39 finished with value: 0.9974059504414768 and parameters: {'max_depth': 4, 'learning_rate': 0.1331007331587899, 'n_estimators': 474}. Best is trial 25 with value: 0.9976274497266301.
[I 2025-12-15 23:07:43,903] Trial 40 finished with value: 0.9972636740842359 and parameters: {'max_depth': 5, 'learning_rate': 0.06118012010817371, 'n_estimators': 443}. Best is trial 25 with value: 0.9976274497266301.
[I 2025-12-15 23:07:44,531] Trial 41 finished with value: 0.997611254844218 and parameters: {'max_depth': 4, 'learning_rate': 0.052772925921626544, 'n_estimators': 419}. Best is trial 25 with value: 0.9976274497266301.
[I 2025-12-15 23:07:45,121] Trial 42 finished with value: 0.997615087802281 and parameters: {'max_depth': 4, 'learning_rate': 0.037730037707110586, 'n_estimators': 370}. Best is trial 25 with value: 0.9976274497266301.
[I 2025-12-15 23:07:45,609] Trial 43 finished with value: 0.9970535721379588 and parameters: {'max_depth': 3, 'learning_rate': 0.020410159476434764, 'n_estimators': 364}. Best is trial 25 with value: 0.9976274497266301.
[I 2025-12-15 23:07:46,220] Trial 44 finished with value: 0.9976468429713995 and parameters: {'max_depth': 4, 'learning_rate': 0.0465960535537886, 'n_estimators': 385}. Best is trial 44 with value: 0.9976468429713995.
[I 2025-12-15 23:07:46,923] Trial 45 finished with value: 0.9974289481898551 and parameters: {'max_depth': 5, 'learning_rate': 0.037689909202744114, 'n_estimators': 389}. Best is trial 44 with value: 0.9976468429713995.
[I 2025-12-15 23:07:47,335] Trial 46 finished with value: 0.9975702853454513 and parameters: {'max_depth': 3, 'learning_rate': 0.06602817668651897, 'n_estimators': 306}. Best is trial 44 with value: 0.9976468429713995.
[I 2025-12-15 23:07:47,730] Trial 47 finished with value: 0.9973985891312895 and parameters: {'max_depth': 2, 'learning_rate': 0.26166963798303666, 'n_estimators': 366}. Best is trial 44 with value: 0.9976468429713995.
[I 2025-12-15 23:07:48,354] Trial 48 finished with value: 0.9973560204513443 and parameters: {'max_depth': 4, 'learning_rate': 0.09912050291307997, 'n_estimators': 390}. Best is trial 44 with value: 0.9976468429713995.
[I 2025-12-15 23:07:48,981] Trial 49 finished with value: 0.9973428462444919 and parameters: {'max_depth': 5, 'learning_rate': 0.08000455480827537, 'n_estimators': 338}. Best is trial 44 with value: 0.9976468429713995.
[I 2025-12-15 23:07:49,484] Trial 50 finished with value: 0.9975308134925506 and parameters: {'max_depth': 3, 'learning_rate': 0.12260749085894113, 'n_estimators': 372}. Best is trial 44 with value: 0.9976468429713995.
[I 2025-12-15 23:07:50,156] Trial 51 finished with value: 0.997589475519595 and parameters: {'max_depth': 4, 'learning_rate': 0.04990427179234785, 'n_estimators': 447}. Best is trial 44 with value: 0.9976468429713995.
[I 2025-12-15 23:07:50,819] Trial 52 finished with value: 0.9976453960931903 and parameters: {'max_depth': 4, 'learning_rate': 0.0453796546236706, 'n_estimators': 425}. Best is trial 44 with value: 0.9976468429713995.
[I 2025-12-15 23:07:51,551] Trial 53 finished with value: 0.9973226407172191 and parameters: {'max_depth': 5, 'learning_rate': 0.018166120620882607, 'n_estimators': 432}. Best is trial 44 with value: 0.9976468429713995.
[I 2025-12-15 23:07:52,075] Trial 54 finished with value: 0.9974596372381878 and parameters: {'max_depth': 3, 'learning_rate': 0.0325081123193202, 'n_estimators': 398}. Best is trial 44 with value: 0.9976468429713995.
[I 2025-12-15 23:07:52,766] Trial 55 finished with value: 0.9976115340663285 and parameters: {'max_depth': 4, 'learning_rate': 0.043132023647232835, 'n_estimators': 466}. Best is trial 44 with value: 0.9976468429713995.
[I 2025-12-15 23:07:53,438] Trial 56 finished with value: 0.9975950853456342 and parameters: {'max_depth': 4, 'learning_rate': 0.06461728840096183, 'n_estimators': 430}. Best is trial 44 with value: 0.9976468429713995.
[I 2025-12-15 23:07:53,978] Trial 57 finished with value: 0.9973394448115086 and parameters: {'max_depth': 3, 'learning_rate': 0.22211111849483156, 'n_estimators': 382}. Best is trial 44 with value: 0.9976468429713995.
[I 2025-12-15 23:07:54,410] Trial 58 finished with value: 0.9974155709123768 and parameters: {'max_depth': 2, 'learning_rate': 0.08668666799062295, 'n_estimators': 400}. Best is trial 44 with value: 0.9976468429713995.
[I 2025-12-15 23:07:54,893] Trial 59 finished with value: 0.9972275528966615 and parameters: {'max_depth': 5, 'learning_rate': 0.10405421648426066, 'n_estimators': 255}. Best is trial 44 with value: 0.9976468429713995.
[I 2025-12-15 23:07:55,442] Trial 60 finished with value: 0.997232299672541 and parameters: {'max_depth': 4, 'learning_rate': 0.16284571908089746, 'n_estimators': 344}. Best is trial 44 with value: 0.9976468429713995.
[I 2025-12-15 23:07:56,159] Trial 61 finished with value: 0.997600415949563 and parameters: {'max_depth': 4, 'learning_rate': 0.04142061674314215, 'n_estimators': 463}. Best is trial 44 with value: 0.9976468429713995.
[I 2025-12-15 23:07:56,758] Trial 62 finished with value: 0.9974754005955196 and parameters: {'max_depth': 3, 'learning_rate': 0.029381212186314766, 'n_estimators': 479}. Best is trial 44 with value: 0.9976468429713995.
[I 2025-12-15 23:07:57,414] Trial 63 finished with value: 0.9976406493173109 and parameters: {'max_depth': 4, 'learning_rate': 0.04865439335844815, 'n_estimators': 447}. Best is trial 44 with value: 0.9976468429713995.
[I 2025-12-15 23:07:58,148] Trial 64 finished with value: 0.9972538759265384 and parameters: {'max_depth': 5, 'learning_rate': 0.07185903617972317, 'n_estimators': 426}. Best is trial 44 with value: 0.9976468429713995.
[I 2025-12-15 23:07:58,808] Trial 65 finished with value: 0.9975964560723588 and parameters: {'max_depth': 4, 'learning_rate': 0.05837134588802542, 'n_estimators': 452}. Best is trial 44 with value: 0.9976468429713995.
[I 2025-12-15 23:07:59,404] Trial 66 finished with value: 0.9971984757214216 and parameters: {'max_depth': 3, 'learning_rate': 0.018916782509869775, 'n_estimators': 452}. Best is trial 44 with value: 0.9976468429713995.
[I 2025-12-15 23:08:00,188] Trial 67 finished with value: 0.9970727623121022 and parameters: {'max_depth': 6, 'learning_rate': 0.04707917042945755, 'n_estimators': 407}. Best is trial 44 with value: 0.9976468429713995.
[I 2025-12-15 23:08:01,306] Trial 68 finished with value: 0.9969373649723122 and parameters: {'max_depth': 9, 'learning_rate': 0.05691671288473979, 'n_estimators': 376}. Best is trial 44 with value: 0.9976468429713995.
[I 2025-12-15 23:08:01,972] Trial 69 finished with value: 0.9975230206572833 and parameters: {'max_depth': 4, 'learning_rate': 0.09110674258755795, 'n_estimators': 440}. Best is trial 44 with value: 0.9976468429713995.
[I 2025-12-15 23:08:02,589] Trial 70 finished with value: 0.9974279836043823 and parameters: {'max_depth': 5, 'learning_rate': 0.037430092535918, 'n_estimators': 359}. Best is trial 44 with value: 0.9976468429713995.
[I 2025-12-15 23:08:03,276] Trial 71 finished with value: 0.9976259774645928 and parameters: {'max_depth': 4, 'learning_rate': 0.04508970122961686, 'n_estimators': 464}. Best is trial 44 with value: 0.9976468429713995.
[I 2025-12-15 23:08:03,917] Trial 72 finished with value: 0.9976125494194579 and parameters: {'max_depth': 4, 'learning_rate': 0.07443449207226387, 'n_estimators': 421}. Best is trial 44 with value: 0.9976468429713995.
[I 2025-12-15 23:08:04,594] Trial 73 finished with value: 0.997142517072084 and parameters: {'max_depth': 3, 'learning_rate': 0.010755349946329741, 'n_estimators': 494}. Best is trial 44 with value: 0.9976468429713995.
[I 2025-12-15 23:08:05,260] Trial 74 finished with value: 0.9976289219886677 and parameters: {'max_depth': 4, 'learning_rate': 0.029961297079884257, 'n_estimators': 455}. Best is trial 44 with value: 0.9976468429713995.
[I 2025-12-15 23:08:06,013] Trial 75 finished with value: 0.9976434669222446 and parameters: {'max_depth': 4, 'learning_rate': 0.031022431382476588, 'n_estimators': 475}. Best is trial 44 with value: 0.9976468429713995.
[I 2025-12-15 23:08:06,736] Trial 76 finished with value: 0.997638136318316 and parameters: {'max_depth': 4, 'learning_rate': 0.025723102921976104, 'n_estimators': 477}. Best is trial 44 with value: 0.9976468429713995.
[I 2025-12-15 23:08:07,572] Trial 77 finished with value: 0.9973685854463191 and parameters: {'max_depth': 5, 'learning_rate': 0.022358461288263604, 'n_estimators': 486}. Best is trial 44 with value: 0.9976468429713995.
[I 2025-12-15 23:08:08,197] Trial 78 finished with value: 0.997491823932386 and parameters: {'max_depth': 3, 'learning_rate': 0.03242906870078774, 'n_estimators': 473}. Best is trial 44 with value: 0.9976468429713995.
[I 2025-12-15 23:08:08,882] Trial 79 finished with value: 0.9975665285388731 and parameters: {'max_depth': 4, 'learning_rate': 0.016417034187516083, 'n_estimators': 457}. Best is trial 44 with value: 0.9976468429713995.
[I 2025-12-15 23:08:09,585] Trial 80 finished with value: 0.9976125240356296 and parameters: {'max_depth': 4, 'learning_rate': 0.025902292855995893, 'n_estimators': 477}. Best is trial 44 with value: 0.9976468429713995.
[I 2025-12-15 23:08:10,370] Trial 81 finished with value: 0.997602624342619 and parameters: {'max_depth': 4, 'learning_rate': 0.05075066011148848, 'n_estimators': 499}. Best is trial 44 with value: 0.9976468429713995.
[I 2025-12-15 23:08:11,049] Trial 82 finished with value: 0.9976072188155292 and parameters: {'max_depth': 4, 'learning_rate': 0.044590925665749744, 'n_estimators': 437}. Best is trial 44 with value: 0.9976468429713995.
[I 2025-12-15 23:08:11,844] Trial 83 finished with value: 0.9973825211680184 and parameters: {'max_depth': 5, 'learning_rate': 0.03205702256730253, 'n_estimators': 469}. Best is trial 44 with value: 0.9976468429713995.
[I 2025-12-15 23:08:12,453] Trial 84 finished with value: 0.9976171946600245 and parameters: {'max_depth': 3, 'learning_rate': 0.05492218101384632, 'n_estimators': 486}. Best is trial 44 with value: 0.9976468429713995.
[I 2025-12-15 23:08:13,053] Trial 85 finished with value: 0.9976711606788459 and parameters: {'max_depth': 3, 'learning_rate': 0.05367593086638551, 'n_estimators': 480}. Best is trial 85 with value: 0.9976711606788459.
[I 2025-12-15 23:08:13,544] Trial 86 finished with value: 0.9971118534075797 and parameters: {'max_depth': 2, 'learning_rate': 0.04321554655081721, 'n_estimators': 456}. Best is trial 85 with value: 0.9976711606788459.
[I 2025-12-15 23:08:14,114] Trial 87 finished with value: 0.9976289219886675 and parameters: {'max_depth': 3, 'learning_rate': 0.06785797866461038, 'n_estimators': 447}. Best is trial 85 with value: 0.9976711606788459.
[I 2025-12-15 23:08:14,371] Trial 88 finished with value: 0.9974497121613489 and parameters: {'max_depth': 3, 'learning_rate': 0.08013389214407794, 'n_estimators': 162}. Best is trial 85 with value: 0.9976711606788459.
[I 2025-12-15 23:08:14,868] Trial 89 finished with value: 0.996808618195519 and parameters: {'max_depth': 2, 'learning_rate': 0.02658175490962948, 'n_estimators': 446}. Best is trial 85 with value: 0.9976711606788459.
[I 2025-12-15 23:08:15,460] Trial 90 finished with value: 0.9976084372392843 and parameters: {'max_depth': 3, 'learning_rate': 0.06776711362194288, 'n_estimators': 478}. Best is trial 85 with value: 0.9976711606788459.

Thời gian tìm kiếm siêu tham số: 128.47 giây
Siêu tham số tốt nhất: {'max_depth': 4, 'learning_rate': 0.04089466384184448, 'n_estimators': 425}
AUC: 0.9977657154390104
Accuracy: 0.981604386091473
Precision: 0.9931362196409715
Recall: 0.9426208970182911
F1 Score: 0.9672194369456228
Matthews Correlation Coefficient: 0.9550745911205134

Ma trận nhầm lẫn:
[[9845   26]
 [ 229 3762]]

Báo cáo phân loại:
              precision    recall  f1-score   support

           0       0.98      1.00      0.99      9871
           1       0.99      0.94      0.97      3991

    accuracy                           0.98     13862
   macro avg       0.99      0.97      0.98     13862
weighted avg       0.98      0.98      0.98     13862

Tổng thời gian thực thi: 129.17 giây